export const JWT = 'GD_jwt'
export const CREDS = 'GD_creds'
export const DESTINATION_PATH = 'GD_destinationPath'
export const IS_LOGGED_IN = 'GD_isLoggedIn'
export const GD_USER_MNEMONIC = 'GD_mnemonic'
