export const USE_DESKTOP = 'GOODDAPP_useDesktop'
export const JWT = 'GoodDAPP_jwt'
export const CREDS = 'GoodDAPP_creds'
export const DESTINATION_PATH = 'destinationPath'
export const IS_LOGGED_IN = 'GOODDAPP_isLoggedIn'
export const GD_USER_MNEMONIC = 'GD_USER_MNEMONIC'
