// flow-typed signature: c7e1ae408472b1876b4b24ce2119b67e
// flow-typed version: <<STUB>>/babel-plugin-named-asset-import_v^0.2.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-named-asset-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-named-asset-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-named-asset-import/index' {
  declare module.exports: $Exports<'babel-plugin-named-asset-import'>;
}
declare module 'babel-plugin-named-asset-import/index.js' {
  declare module.exports: $Exports<'babel-plugin-named-asset-import'>;
}
