// flow-typed signature: 021e3773fb217a5355cc57b3dbb4055c
// flow-typed version: <<STUB>>/bfj_v6.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bfj'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bfj' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bfj/src/datastream' {
  declare module.exports: any;
}

declare module 'bfj/src/error' {
  declare module.exports: any;
}

declare module 'bfj/src/eventify' {
  declare module.exports: any;
}

declare module 'bfj/src/events' {
  declare module.exports: any;
}

declare module 'bfj/src/index' {
  declare module.exports: any;
}

declare module 'bfj/src/jsonstream' {
  declare module.exports: any;
}

declare module 'bfj/src/match' {
  declare module.exports: any;
}

declare module 'bfj/src/memory' {
  declare module.exports: any;
}

declare module 'bfj/src/parse' {
  declare module.exports: any;
}

declare module 'bfj/src/promise' {
  declare module.exports: any;
}

declare module 'bfj/src/read' {
  declare module.exports: any;
}

declare module 'bfj/src/stream' {
  declare module.exports: any;
}

declare module 'bfj/src/streamify' {
  declare module.exports: any;
}

declare module 'bfj/src/stringify' {
  declare module.exports: any;
}

declare module 'bfj/src/unpipe' {
  declare module.exports: any;
}

declare module 'bfj/src/walk' {
  declare module.exports: any;
}

declare module 'bfj/src/write' {
  declare module.exports: any;
}

declare module 'bfj/test/integration' {
  declare module.exports: any;
}

declare module 'bfj/test/performance' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/datastream' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/error' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/eventify' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/jsonstream' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/match' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/parse' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/read' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/streamify' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/stringify' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/unpipe' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/walk' {
  declare module.exports: any;
}

declare module 'bfj/test/unit/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bfj/src/datastream.js' {
  declare module.exports: $Exports<'bfj/src/datastream'>;
}
declare module 'bfj/src/error.js' {
  declare module.exports: $Exports<'bfj/src/error'>;
}
declare module 'bfj/src/eventify.js' {
  declare module.exports: $Exports<'bfj/src/eventify'>;
}
declare module 'bfj/src/events.js' {
  declare module.exports: $Exports<'bfj/src/events'>;
}
declare module 'bfj/src/index.js' {
  declare module.exports: $Exports<'bfj/src/index'>;
}
declare module 'bfj/src/jsonstream.js' {
  declare module.exports: $Exports<'bfj/src/jsonstream'>;
}
declare module 'bfj/src/match.js' {
  declare module.exports: $Exports<'bfj/src/match'>;
}
declare module 'bfj/src/memory.js' {
  declare module.exports: $Exports<'bfj/src/memory'>;
}
declare module 'bfj/src/parse.js' {
  declare module.exports: $Exports<'bfj/src/parse'>;
}
declare module 'bfj/src/promise.js' {
  declare module.exports: $Exports<'bfj/src/promise'>;
}
declare module 'bfj/src/read.js' {
  declare module.exports: $Exports<'bfj/src/read'>;
}
declare module 'bfj/src/stream.js' {
  declare module.exports: $Exports<'bfj/src/stream'>;
}
declare module 'bfj/src/streamify.js' {
  declare module.exports: $Exports<'bfj/src/streamify'>;
}
declare module 'bfj/src/stringify.js' {
  declare module.exports: $Exports<'bfj/src/stringify'>;
}
declare module 'bfj/src/unpipe.js' {
  declare module.exports: $Exports<'bfj/src/unpipe'>;
}
declare module 'bfj/src/walk.js' {
  declare module.exports: $Exports<'bfj/src/walk'>;
}
declare module 'bfj/src/write.js' {
  declare module.exports: $Exports<'bfj/src/write'>;
}
declare module 'bfj/test/integration.js' {
  declare module.exports: $Exports<'bfj/test/integration'>;
}
declare module 'bfj/test/performance.js' {
  declare module.exports: $Exports<'bfj/test/performance'>;
}
declare module 'bfj/test/unit/datastream.js' {
  declare module.exports: $Exports<'bfj/test/unit/datastream'>;
}
declare module 'bfj/test/unit/error.js' {
  declare module.exports: $Exports<'bfj/test/unit/error'>;
}
declare module 'bfj/test/unit/eventify.js' {
  declare module.exports: $Exports<'bfj/test/unit/eventify'>;
}
declare module 'bfj/test/unit/jsonstream.js' {
  declare module.exports: $Exports<'bfj/test/unit/jsonstream'>;
}
declare module 'bfj/test/unit/match.js' {
  declare module.exports: $Exports<'bfj/test/unit/match'>;
}
declare module 'bfj/test/unit/parse.js' {
  declare module.exports: $Exports<'bfj/test/unit/parse'>;
}
declare module 'bfj/test/unit/read.js' {
  declare module.exports: $Exports<'bfj/test/unit/read'>;
}
declare module 'bfj/test/unit/streamify.js' {
  declare module.exports: $Exports<'bfj/test/unit/streamify'>;
}
declare module 'bfj/test/unit/stringify.js' {
  declare module.exports: $Exports<'bfj/test/unit/stringify'>;
}
declare module 'bfj/test/unit/unpipe.js' {
  declare module.exports: $Exports<'bfj/test/unit/unpipe'>;
}
declare module 'bfj/test/unit/walk.js' {
  declare module.exports: $Exports<'bfj/test/unit/walk'>;
}
declare module 'bfj/test/unit/write.js' {
  declare module.exports: $Exports<'bfj/test/unit/write'>;
}
