// flow-typed signature: 687025e73b1207de7ddf96b85cebbebc
// flow-typed version: <<STUB>>/bip39-light_v^1.0.7/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bip39-light'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bip39-light' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bip39-light/test/index' {
  declare module.exports: any;
}

declare module 'bip39-light/test/readme' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bip39-light/index' {
  declare module.exports: $Exports<'bip39-light'>;
}
declare module 'bip39-light/index.js' {
  declare module.exports: $Exports<'bip39-light'>;
}
declare module 'bip39-light/test/index.js' {
  declare module.exports: $Exports<'bip39-light/test/index'>;
}
declare module 'bip39-light/test/readme.js' {
  declare module.exports: $Exports<'bip39-light/test/readme'>;
}
