// flow-typed signature: 7a1c059af3538cf35d9b70797b2fc815
// flow-typed version: <<STUB>>/eslint-config-react-app_v^3.0.7/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-react-app/index' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
declare module 'eslint-config-react-app/index.js' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
