// flow-typed signature: fe24d33ed69c5ad4b855079df56a8c51
// flow-typed version: <<STUB>>/eslint-plugin-dependencies_v^2.4.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-dependencies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-dependencies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-dependencies/_helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-dependencies/case-sensitive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-dependencies/no-cycles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-dependencies/no-unresolved' {
  declare module.exports: any;
}

declare module 'eslint-plugin-dependencies/require-json-ext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-dependencies/_helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-dependencies/_helpers'>;
}
declare module 'eslint-plugin-dependencies/case-sensitive.js' {
  declare module.exports: $Exports<'eslint-plugin-dependencies/case-sensitive'>;
}
declare module 'eslint-plugin-dependencies/index' {
  declare module.exports: $Exports<'eslint-plugin-dependencies'>;
}
declare module 'eslint-plugin-dependencies/index.js' {
  declare module.exports: $Exports<'eslint-plugin-dependencies'>;
}
declare module 'eslint-plugin-dependencies/no-cycles.js' {
  declare module.exports: $Exports<'eslint-plugin-dependencies/no-cycles'>;
}
declare module 'eslint-plugin-dependencies/no-unresolved.js' {
  declare module.exports: $Exports<'eslint-plugin-dependencies/no-unresolved'>;
}
declare module 'eslint-plugin-dependencies/require-json-ext.js' {
  declare module.exports: $Exports<'eslint-plugin-dependencies/require-json-ext'>;
}
