// flow-typed signature: c593e0760c91ed2c9e06a5af209bc45c
// flow-typed version: <<STUB>>/ethereumjs-wallet_v^0.6.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-wallet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-wallet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-wallet/hdkey' {
  declare module.exports: any;
}

declare module 'ethereumjs-wallet/provider-engine' {
  declare module.exports: any;
}

declare module 'ethereumjs-wallet/test/hdkey' {
  declare module.exports: any;
}

declare module 'ethereumjs-wallet/test/index' {
  declare module.exports: any;
}

declare module 'ethereumjs-wallet/thirdparty' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-wallet/hdkey.js' {
  declare module.exports: $Exports<'ethereumjs-wallet/hdkey'>;
}
declare module 'ethereumjs-wallet/index' {
  declare module.exports: $Exports<'ethereumjs-wallet'>;
}
declare module 'ethereumjs-wallet/index.js' {
  declare module.exports: $Exports<'ethereumjs-wallet'>;
}
declare module 'ethereumjs-wallet/provider-engine.js' {
  declare module.exports: $Exports<'ethereumjs-wallet/provider-engine'>;
}
declare module 'ethereumjs-wallet/test/hdkey.js' {
  declare module.exports: $Exports<'ethereumjs-wallet/test/hdkey'>;
}
declare module 'ethereumjs-wallet/test/index.js' {
  declare module.exports: $Exports<'ethereumjs-wallet/test/index'>;
}
declare module 'ethereumjs-wallet/thirdparty.js' {
  declare module.exports: $Exports<'ethereumjs-wallet/thirdparty'>;
}
