// flow-typed signature: bbb471df32eaa2c397aa3540ab636ff9
// flow-typed version: <<STUB>>/exif-react-avatar-edit_v^0.8.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exif-react-avatar-edit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exif-react-avatar-edit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exif-react-avatar-edit/lib/react-avatar' {
  declare module.exports: any;
}

declare module 'exif-react-avatar-edit/src/avatar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exif-react-avatar-edit/lib/react-avatar.js' {
  declare module.exports: $Exports<'exif-react-avatar-edit/lib/react-avatar'>;
}
declare module 'exif-react-avatar-edit/src/avatar.jsx' {
  declare module.exports: $Exports<'exif-react-avatar-edit/src/avatar'>;
}
