// flow-typed signature: 2da0bc19ba0bfd4af7e1e6130c0e083a
// flow-typed version: <<STUB>>/fork-ts-checker-webpack-plugin-alt_v0.4.14/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fork-ts-checker-webpack-plugin-alt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fork-ts-checker-webpack-plugin-alt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fork-ts-checker-webpack-plugin-alt/lib/CancellationToken' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/cluster' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/FilesRegister' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/FilesWatcher' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/formatter/codeframeFormatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/formatter/defaultFormatter' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/IncrementalChecker' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/index' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/Message' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/NormalizedMessage' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/OperationCanceledException' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/service' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/TypeScriptInstance' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/VueProgram' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/WorkResult' {
  declare module.exports: any;
}

declare module 'fork-ts-checker-webpack-plugin-alt/lib/WorkSet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fork-ts-checker-webpack-plugin-alt/lib/CancellationToken.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/CancellationToken'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/cluster.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/cluster'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/FilesRegister.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/FilesRegister'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/FilesWatcher.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/FilesWatcher'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/formatter/codeframeFormatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/formatter/codeframeFormatter'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/formatter/defaultFormatter.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/formatter/defaultFormatter'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/IncrementalChecker.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/IncrementalChecker'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/index.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/index'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/Message.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/Message'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/NormalizedMessage.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/NormalizedMessage'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/OperationCanceledException.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/OperationCanceledException'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/service.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/service'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/TypeScriptInstance.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/TypeScriptInstance'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/VueProgram.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/VueProgram'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/WorkResult.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/WorkResult'>;
}
declare module 'fork-ts-checker-webpack-plugin-alt/lib/WorkSet.js' {
  declare module.exports: $Exports<'fork-ts-checker-webpack-plugin-alt/lib/WorkSet'>;
}
