// flow-typed signature: 2807c9d8fd71449339e8acd64f708b00
// flow-typed version: <<STUB>>/FormData_v^0.10.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'FormData'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'FormData' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'FormData/FormData' {
  declare module.exports: any;
}

// Filename aliases
declare module 'FormData/FormData.js' {
  declare module.exports: $Exports<'FormData/FormData'>;
}
