// flow-typed signature: 04a9bac3f91adcea91845bffdc91f2bd
// flow-typed version: <<STUB>>/ganache-cli_v^6.4.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ganache-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ganache-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ganache-cli/args' {
  declare module.exports: any;
}

declare module 'ganache-cli/build/ganache-core.node.cli' {
  declare module.exports: any;
}

declare module 'ganache-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ganache-cli/args.js' {
  declare module.exports: $Exports<'ganache-cli/args'>;
}
declare module 'ganache-cli/build/ganache-core.node.cli.js' {
  declare module.exports: $Exports<'ganache-cli/build/ganache-core.node.cli'>;
}
declare module 'ganache-cli/cli.js' {
  declare module.exports: $Exports<'ganache-cli/cli'>;
}
