// flow-typed signature: 5b618b928f2ea2c2828f9d633f4585e3
// flow-typed version: <<STUB>>/gun_v^0.2019.515/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gun'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gun' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gun/as' {
  declare module.exports: any;
}

declare module 'gun/axe' {
  declare module.exports: any;
}

declare module 'gun/examples/angular/karma.conf' {
  declare module.exports: any;
}

declare module 'gun/examples/angular/protractor.conf' {
  declare module.exports: any;
}

declare module 'gun/examples/angular/server' {
  declare module.exports: any;
}

declare module 'gun/examples/express' {
  declare module.exports: any;
}

declare module 'gun/examples/hapi' {
  declare module.exports: any;
}

declare module 'gun/examples/http-external-ws' {
  declare module.exports: any;
}

declare module 'gun/examples/http' {
  declare module.exports: any;
}

declare module 'gun/examples/jquery' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/index' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/shim' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/App/app' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/App/Demo' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/App/index' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/App/PolyFillCrypto' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/extensions/asyncStorageAdapter' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/extensions/sea' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/asyncSerialize' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/compat' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/index' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/MainWorker' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/serializeBinary' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/WebViewWorker' {
  declare module.exports: any;
}

declare module 'gun/examples/react-native/src/webview-crypto/webViewWorkerString' {
  declare module.exports: any;
}

declare module 'gun/examples/react/server' {
  declare module.exports: any;
}

declare module 'gun/examples/react/src/App' {
  declare module.exports: any;
}

declare module 'gun/examples/react/src/App.test' {
  declare module.exports: any;
}

declare module 'gun/examples/react/src/Chat' {
  declare module.exports: any;
}

declare module 'gun/examples/react/src/index' {
  declare module.exports: any;
}

declare module 'gun/examples/react/src/Json' {
  declare module.exports: any;
}

declare module 'gun/examples/react/src/Todos' {
  declare module.exports: any;
}

declare module 'gun/gun' {
  declare module.exports: any;
}

declare module 'gun/gun.min' {
  declare module.exports: any;
}

declare module 'gun/lib/aws' {
  declare module.exports: any;
}

declare module 'gun/lib/bye' {
  declare module.exports: any;
}

declare module 'gun/lib/cryptomodules' {
  declare module.exports: any;
}

declare module 'gun/lib/debug' {
  declare module.exports: any;
}

declare module 'gun/lib/erase' {
  declare module.exports: any;
}

declare module 'gun/lib/evict' {
  declare module.exports: any;
}

declare module 'gun/lib/file' {
  declare module.exports: any;
}

declare module 'gun/lib/forget' {
  declare module.exports: any;
}

declare module 'gun/lib/fsrm' {
  declare module.exports: any;
}

declare module 'gun/lib/fun' {
  declare module.exports: any;
}

declare module 'gun/lib/http' {
  declare module.exports: any;
}

declare module 'gun/lib/hub' {
  declare module.exports: any;
}

declare module 'gun/lib/ipfs' {
  declare module.exports: any;
}

declare module 'gun/lib/jsonp' {
  declare module.exports: any;
}

declare module 'gun/lib/later' {
  declare module.exports: any;
}

declare module 'gun/lib/les' {
  declare module.exports: any;
}

declare module 'gun/lib/list' {
  declare module.exports: any;
}

declare module 'gun/lib/load' {
  declare module.exports: any;
}

declare module 'gun/lib/match' {
  declare module.exports: any;
}

declare module 'gun/lib/memdisk' {
  declare module.exports: any;
}

declare module 'gun/lib/meta' {
  declare module.exports: any;
}

declare module 'gun/lib/monotype' {
  declare module.exports: any;
}

declare module 'gun/lib/multicast' {
  declare module.exports: any;
}

declare module 'gun/lib/normalize' {
  declare module.exports: any;
}

declare module 'gun/lib/not' {
  declare module.exports: any;
}

declare module 'gun/lib/open' {
  declare module.exports: any;
}

declare module 'gun/lib/path' {
  declare module.exports: any;
}

declare module 'gun/lib/radisk' {
  declare module.exports: any;
}

declare module 'gun/lib/radix' {
  declare module.exports: any;
}

declare module 'gun/lib/reboot' {
  declare module.exports: any;
}

declare module 'gun/lib/rfs' {
  declare module.exports: any;
}

declare module 'gun/lib/rindexed' {
  declare module.exports: any;
}

declare module 'gun/lib/rls' {
  declare module.exports: any;
}

declare module 'gun/lib/rmem' {
  declare module.exports: any;
}

declare module 'gun/lib/role' {
  declare module.exports: any;
}

declare module 'gun/lib/rs3' {
  declare module.exports: any;
}

declare module 'gun/lib/serve' {
  declare module.exports: any;
}

declare module 'gun/lib/server' {
  declare module.exports: any;
}

declare module 'gun/lib/shim' {
  declare module.exports: any;
}

declare module 'gun/lib/space' {
  declare module.exports: any;
}

declare module 'gun/lib/stats' {
  declare module.exports: any;
}

declare module 'gun/lib/store' {
  declare module.exports: any;
}

declare module 'gun/lib/super' {
  declare module.exports: any;
}

declare module 'gun/lib/then' {
  declare module.exports: any;
}

declare module 'gun/lib/time' {
  declare module.exports: any;
}

declare module 'gun/lib/tmp.test.sql' {
  declare module.exports: any;
}

declare module 'gun/lib/unbuild' {
  declare module.exports: any;
}

declare module 'gun/lib/unset' {
  declare module.exports: any;
}

declare module 'gun/lib/untitled' {
  declare module.exports: any;
}

declare module 'gun/lib/upload' {
  declare module.exports: any;
}

declare module 'gun/lib/uws' {
  declare module.exports: any;
}

declare module 'gun/lib/verify' {
  declare module.exports: any;
}

declare module 'gun/lib/webrtc' {
  declare module.exports: any;
}

declare module 'gun/lib/wire' {
  declare module.exports: any;
}

declare module 'gun/lib/ws' {
  declare module.exports: any;
}

declare module 'gun/lib/wsp' {
  declare module.exports: any;
}

declare module 'gun/lib/wsproto' {
  declare module.exports: any;
}

declare module 'gun/nts' {
  declare module.exports: any;
}

declare module 'gun/sea' {
  declare module.exports: any;
}

declare module 'gun/sea/aeskey' {
  declare module.exports: any;
}

declare module 'gun/sea/array' {
  declare module.exports: any;
}

declare module 'gun/sea/buffer' {
  declare module.exports: any;
}

declare module 'gun/sea/create' {
  declare module.exports: any;
}

declare module 'gun/sea/decrypt' {
  declare module.exports: any;
}

declare module 'gun/sea/encrypt' {
  declare module.exports: any;
}

declare module 'gun/sea/https' {
  declare module.exports: any;
}

declare module 'gun/sea/index' {
  declare module.exports: any;
}

declare module 'gun/sea/pair' {
  declare module.exports: any;
}

declare module 'gun/sea/root' {
  declare module.exports: any;
}

declare module 'gun/sea/sea' {
  declare module.exports: any;
}

declare module 'gun/sea/secret' {
  declare module.exports: any;
}

declare module 'gun/sea/settings' {
  declare module.exports: any;
}

declare module 'gun/sea/sha1' {
  declare module.exports: any;
}

declare module 'gun/sea/sha256' {
  declare module.exports: any;
}

declare module 'gun/sea/shim' {
  declare module.exports: any;
}

declare module 'gun/sea/sign' {
  declare module.exports: any;
}

declare module 'gun/sea/then' {
  declare module.exports: any;
}

declare module 'gun/sea/user' {
  declare module.exports: any;
}

declare module 'gun/sea/verify' {
  declare module.exports: any;
}

declare module 'gun/sea/work' {
  declare module.exports: any;
}

declare module 'gun/src/adapters/localStorage' {
  declare module.exports: any;
}

declare module 'gun/src/adapters/mesh' {
  declare module.exports: any;
}

declare module 'gun/src/adapters/websocket' {
  declare module.exports: any;
}

declare module 'gun/src/ask' {
  declare module.exports: any;
}

declare module 'gun/src/back' {
  declare module.exports: any;
}

declare module 'gun/src/chain' {
  declare module.exports: any;
}

declare module 'gun/src/dup' {
  declare module.exports: any;
}

declare module 'gun/src/get' {
  declare module.exports: any;
}

declare module 'gun/src/graph' {
  declare module.exports: any;
}

declare module 'gun/src/HAM' {
  declare module.exports: any;
}

declare module 'gun/src/index' {
  declare module.exports: any;
}

declare module 'gun/src/map' {
  declare module.exports: any;
}

declare module 'gun/src/node' {
  declare module.exports: any;
}

declare module 'gun/src/on' {
  declare module.exports: any;
}

declare module 'gun/src/onto' {
  declare module.exports: any;
}

declare module 'gun/src/polyfill/unbuild' {
  declare module.exports: any;
}

declare module 'gun/src/put' {
  declare module.exports: any;
}

declare module 'gun/src/root' {
  declare module.exports: any;
}

declare module 'gun/src/set' {
  declare module.exports: any;
}

declare module 'gun/src/state' {
  declare module.exports: any;
}

declare module 'gun/src/type' {
  declare module.exports: any;
}

declare module 'gun/src/val' {
  declare module.exports: any;
}

declare module 'gun/test/abc' {
  declare module.exports: any;
}

declare module 'gun/test/axe/holy-grail' {
  declare module.exports: any;
}

declare module 'gun/test/common' {
  declare module.exports: any;
}

declare module 'gun/test/expect' {
  declare module.exports: any;
}

declare module 'gun/test/https/test' {
  declare module.exports: any;
}

declare module 'gun/test/index' {
  declare module.exports: any;
}

declare module 'gun/test/json2' {
  declare module.exports: any;
}

declare module 'gun/test/mocha' {
  declare module.exports: any;
}

declare module 'gun/test/old/all' {
  declare module.exports: any;
}

declare module 'gun/test/old/interface' {
  declare module.exports: any;
}

declare module 'gun/test/old/performance' {
  declare module.exports: any;
}

declare module 'gun/test/old/server' {
  declare module.exports: any;
}

declare module 'gun/test/old/set' {
  declare module.exports: any;
}

declare module 'gun/test/old/shoot' {
  declare module.exports: any;
}

declare module 'gun/test/old/shotgun' {
  declare module.exports: any;
}

declare module 'gun/test/old/tmp' {
  declare module.exports: any;
}

declare module 'gun/test/panic/b2s2s2b' {
  declare module.exports: any;
}

declare module 'gun/test/panic/curl-server' {
  declare module.exports: any;
}

declare module 'gun/test/panic/e2e/distributed' {
  declare module.exports: any;
}

declare module 'gun/test/panic/e2e/holy/grail' {
  declare module.exports: any;
}

declare module 'gun/test/panic/e2e/holy/gun-server' {
  declare module.exports: any;
}

declare module 'gun/test/panic/holy-grail' {
  declare module.exports: any;
}

declare module 'gun/test/panic/load' {
  declare module.exports: any;
}

declare module 'gun/test/panic/radisk' {
  declare module.exports: any;
}

declare module 'gun/test/panic/s2s-all-delayed-peer-add' {
  declare module.exports: any;
}

declare module 'gun/test/panic/s2s-all' {
  declare module.exports: any;
}

declare module 'gun/test/panic/scale' {
  declare module.exports: any;
}

declare module 'gun/test/panic/set' {
  declare module.exports: any;
}

declare module 'gun/test/panic/speak' {
  declare module.exports: any;
}

declare module 'gun/test/panic/users' {
  declare module.exports: any;
}

declare module 'gun/test/panic/who' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/benchmark' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/memdisk' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/perf' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/ptsd' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/radix' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/spam' {
  declare module.exports: any;
}

declare module 'gun/test/ptsd/streampipe' {
  declare module.exports: any;
}

declare module 'gun/test/rad/rad' {
  declare module.exports: any;
}

declare module 'gun/test/radix' {
  declare module.exports: any;
}

declare module 'gun/test/sea/sea_old' {
  declare module.exports: any;
}

declare module 'gun/test/sea/sea' {
  declare module.exports: any;
}

declare module 'gun/test/server/http' {
  declare module.exports: any;
}

declare module 'gun/test/server/node-client' {
  declare module.exports: any;
}

declare module 'gun/test/server/node-write' {
  declare module.exports: any;
}

declare module 'gun/test/tmp/bigsync' {
  declare module.exports: any;
}

declare module 'gun/test/tmp/mitra/client_to_server' {
  declare module.exports: any;
}

declare module 'gun/test/tmp/mitra/gun_https2' {
  declare module.exports: any;
}

declare module 'gun/test/tmp/seanode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gun/as.js' {
  declare module.exports: $Exports<'gun/as'>;
}
declare module 'gun/axe.js' {
  declare module.exports: $Exports<'gun/axe'>;
}
declare module 'gun/examples/angular/karma.conf.js' {
  declare module.exports: $Exports<'gun/examples/angular/karma.conf'>;
}
declare module 'gun/examples/angular/protractor.conf.js' {
  declare module.exports: $Exports<'gun/examples/angular/protractor.conf'>;
}
declare module 'gun/examples/angular/server.js' {
  declare module.exports: $Exports<'gun/examples/angular/server'>;
}
declare module 'gun/examples/express.js' {
  declare module.exports: $Exports<'gun/examples/express'>;
}
declare module 'gun/examples/hapi.js' {
  declare module.exports: $Exports<'gun/examples/hapi'>;
}
declare module 'gun/examples/http-external-ws.js' {
  declare module.exports: $Exports<'gun/examples/http-external-ws'>;
}
declare module 'gun/examples/http.js' {
  declare module.exports: $Exports<'gun/examples/http'>;
}
declare module 'gun/examples/jquery.js' {
  declare module.exports: $Exports<'gun/examples/jquery'>;
}
declare module 'gun/examples/react-native/index.js' {
  declare module.exports: $Exports<'gun/examples/react-native/index'>;
}
declare module 'gun/examples/react-native/shim.js' {
  declare module.exports: $Exports<'gun/examples/react-native/shim'>;
}
declare module 'gun/examples/react-native/src/App/app.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/App/app'>;
}
declare module 'gun/examples/react-native/src/App/Demo.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/App/Demo'>;
}
declare module 'gun/examples/react-native/src/App/index.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/App/index'>;
}
declare module 'gun/examples/react-native/src/App/PolyFillCrypto.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/App/PolyFillCrypto'>;
}
declare module 'gun/examples/react-native/src/extensions/asyncStorageAdapter.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/extensions/asyncStorageAdapter'>;
}
declare module 'gun/examples/react-native/src/extensions/sea.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/extensions/sea'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/asyncSerialize.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/asyncSerialize'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/compat.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/compat'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/index.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/index'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/MainWorker.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/MainWorker'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/serializeBinary.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/serializeBinary'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/WebViewWorker.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/WebViewWorker'>;
}
declare module 'gun/examples/react-native/src/webview-crypto/webViewWorkerString.js' {
  declare module.exports: $Exports<'gun/examples/react-native/src/webview-crypto/webViewWorkerString'>;
}
declare module 'gun/examples/react/server.js' {
  declare module.exports: $Exports<'gun/examples/react/server'>;
}
declare module 'gun/examples/react/src/App.js' {
  declare module.exports: $Exports<'gun/examples/react/src/App'>;
}
declare module 'gun/examples/react/src/App.test.js' {
  declare module.exports: $Exports<'gun/examples/react/src/App.test'>;
}
declare module 'gun/examples/react/src/Chat.js' {
  declare module.exports: $Exports<'gun/examples/react/src/Chat'>;
}
declare module 'gun/examples/react/src/index.js' {
  declare module.exports: $Exports<'gun/examples/react/src/index'>;
}
declare module 'gun/examples/react/src/Json.js' {
  declare module.exports: $Exports<'gun/examples/react/src/Json'>;
}
declare module 'gun/examples/react/src/Todos.js' {
  declare module.exports: $Exports<'gun/examples/react/src/Todos'>;
}
declare module 'gun/gun.js' {
  declare module.exports: $Exports<'gun/gun'>;
}
declare module 'gun/gun.min.js' {
  declare module.exports: $Exports<'gun/gun.min'>;
}
declare module 'gun/index' {
  declare module.exports: $Exports<'gun'>;
}
declare module 'gun/index.js' {
  declare module.exports: $Exports<'gun'>;
}
declare module 'gun/lib/aws.js' {
  declare module.exports: $Exports<'gun/lib/aws'>;
}
declare module 'gun/lib/bye.js' {
  declare module.exports: $Exports<'gun/lib/bye'>;
}
declare module 'gun/lib/cryptomodules.js' {
  declare module.exports: $Exports<'gun/lib/cryptomodules'>;
}
declare module 'gun/lib/debug.js' {
  declare module.exports: $Exports<'gun/lib/debug'>;
}
declare module 'gun/lib/erase.js' {
  declare module.exports: $Exports<'gun/lib/erase'>;
}
declare module 'gun/lib/evict.js' {
  declare module.exports: $Exports<'gun/lib/evict'>;
}
declare module 'gun/lib/file.js' {
  declare module.exports: $Exports<'gun/lib/file'>;
}
declare module 'gun/lib/forget.js' {
  declare module.exports: $Exports<'gun/lib/forget'>;
}
declare module 'gun/lib/fsrm.js' {
  declare module.exports: $Exports<'gun/lib/fsrm'>;
}
declare module 'gun/lib/fun.js' {
  declare module.exports: $Exports<'gun/lib/fun'>;
}
declare module 'gun/lib/http.js' {
  declare module.exports: $Exports<'gun/lib/http'>;
}
declare module 'gun/lib/hub.js' {
  declare module.exports: $Exports<'gun/lib/hub'>;
}
declare module 'gun/lib/ipfs.js' {
  declare module.exports: $Exports<'gun/lib/ipfs'>;
}
declare module 'gun/lib/jsonp.js' {
  declare module.exports: $Exports<'gun/lib/jsonp'>;
}
declare module 'gun/lib/later.js' {
  declare module.exports: $Exports<'gun/lib/later'>;
}
declare module 'gun/lib/les.js' {
  declare module.exports: $Exports<'gun/lib/les'>;
}
declare module 'gun/lib/list.js' {
  declare module.exports: $Exports<'gun/lib/list'>;
}
declare module 'gun/lib/load.js' {
  declare module.exports: $Exports<'gun/lib/load'>;
}
declare module 'gun/lib/match.js' {
  declare module.exports: $Exports<'gun/lib/match'>;
}
declare module 'gun/lib/memdisk.js' {
  declare module.exports: $Exports<'gun/lib/memdisk'>;
}
declare module 'gun/lib/meta.js' {
  declare module.exports: $Exports<'gun/lib/meta'>;
}
declare module 'gun/lib/monotype.js' {
  declare module.exports: $Exports<'gun/lib/monotype'>;
}
declare module 'gun/lib/multicast.js' {
  declare module.exports: $Exports<'gun/lib/multicast'>;
}
declare module 'gun/lib/normalize.js' {
  declare module.exports: $Exports<'gun/lib/normalize'>;
}
declare module 'gun/lib/not.js' {
  declare module.exports: $Exports<'gun/lib/not'>;
}
declare module 'gun/lib/open.js' {
  declare module.exports: $Exports<'gun/lib/open'>;
}
declare module 'gun/lib/path.js' {
  declare module.exports: $Exports<'gun/lib/path'>;
}
declare module 'gun/lib/radisk.js' {
  declare module.exports: $Exports<'gun/lib/radisk'>;
}
declare module 'gun/lib/radix.js' {
  declare module.exports: $Exports<'gun/lib/radix'>;
}
declare module 'gun/lib/reboot.js' {
  declare module.exports: $Exports<'gun/lib/reboot'>;
}
declare module 'gun/lib/rfs.js' {
  declare module.exports: $Exports<'gun/lib/rfs'>;
}
declare module 'gun/lib/rindexed.js' {
  declare module.exports: $Exports<'gun/lib/rindexed'>;
}
declare module 'gun/lib/rls.js' {
  declare module.exports: $Exports<'gun/lib/rls'>;
}
declare module 'gun/lib/rmem.js' {
  declare module.exports: $Exports<'gun/lib/rmem'>;
}
declare module 'gun/lib/role.js' {
  declare module.exports: $Exports<'gun/lib/role'>;
}
declare module 'gun/lib/rs3.js' {
  declare module.exports: $Exports<'gun/lib/rs3'>;
}
declare module 'gun/lib/serve.js' {
  declare module.exports: $Exports<'gun/lib/serve'>;
}
declare module 'gun/lib/server.js' {
  declare module.exports: $Exports<'gun/lib/server'>;
}
declare module 'gun/lib/shim.js' {
  declare module.exports: $Exports<'gun/lib/shim'>;
}
declare module 'gun/lib/space.js' {
  declare module.exports: $Exports<'gun/lib/space'>;
}
declare module 'gun/lib/stats.js' {
  declare module.exports: $Exports<'gun/lib/stats'>;
}
declare module 'gun/lib/store.js' {
  declare module.exports: $Exports<'gun/lib/store'>;
}
declare module 'gun/lib/super.js' {
  declare module.exports: $Exports<'gun/lib/super'>;
}
declare module 'gun/lib/then.js' {
  declare module.exports: $Exports<'gun/lib/then'>;
}
declare module 'gun/lib/time.js' {
  declare module.exports: $Exports<'gun/lib/time'>;
}
declare module 'gun/lib/tmp.test.sql.js' {
  declare module.exports: $Exports<'gun/lib/tmp.test.sql'>;
}
declare module 'gun/lib/unbuild.js' {
  declare module.exports: $Exports<'gun/lib/unbuild'>;
}
declare module 'gun/lib/unset.js' {
  declare module.exports: $Exports<'gun/lib/unset'>;
}
declare module 'gun/lib/untitled.js' {
  declare module.exports: $Exports<'gun/lib/untitled'>;
}
declare module 'gun/lib/upload.js' {
  declare module.exports: $Exports<'gun/lib/upload'>;
}
declare module 'gun/lib/uws.js' {
  declare module.exports: $Exports<'gun/lib/uws'>;
}
declare module 'gun/lib/verify.js' {
  declare module.exports: $Exports<'gun/lib/verify'>;
}
declare module 'gun/lib/webrtc.js' {
  declare module.exports: $Exports<'gun/lib/webrtc'>;
}
declare module 'gun/lib/wire.js' {
  declare module.exports: $Exports<'gun/lib/wire'>;
}
declare module 'gun/lib/ws.js' {
  declare module.exports: $Exports<'gun/lib/ws'>;
}
declare module 'gun/lib/wsp.js' {
  declare module.exports: $Exports<'gun/lib/wsp'>;
}
declare module 'gun/lib/wsproto.js' {
  declare module.exports: $Exports<'gun/lib/wsproto'>;
}
declare module 'gun/nts.js' {
  declare module.exports: $Exports<'gun/nts'>;
}
declare module 'gun/sea.js' {
  declare module.exports: $Exports<'gun/sea'>;
}
declare module 'gun/sea/aeskey.js' {
  declare module.exports: $Exports<'gun/sea/aeskey'>;
}
declare module 'gun/sea/array.js' {
  declare module.exports: $Exports<'gun/sea/array'>;
}
declare module 'gun/sea/buffer.js' {
  declare module.exports: $Exports<'gun/sea/buffer'>;
}
declare module 'gun/sea/create.js' {
  declare module.exports: $Exports<'gun/sea/create'>;
}
declare module 'gun/sea/decrypt.js' {
  declare module.exports: $Exports<'gun/sea/decrypt'>;
}
declare module 'gun/sea/encrypt.js' {
  declare module.exports: $Exports<'gun/sea/encrypt'>;
}
declare module 'gun/sea/https.js' {
  declare module.exports: $Exports<'gun/sea/https'>;
}
declare module 'gun/sea/index.js' {
  declare module.exports: $Exports<'gun/sea/index'>;
}
declare module 'gun/sea/pair.js' {
  declare module.exports: $Exports<'gun/sea/pair'>;
}
declare module 'gun/sea/root.js' {
  declare module.exports: $Exports<'gun/sea/root'>;
}
declare module 'gun/sea/sea.js' {
  declare module.exports: $Exports<'gun/sea/sea'>;
}
declare module 'gun/sea/secret.js' {
  declare module.exports: $Exports<'gun/sea/secret'>;
}
declare module 'gun/sea/settings.js' {
  declare module.exports: $Exports<'gun/sea/settings'>;
}
declare module 'gun/sea/sha1.js' {
  declare module.exports: $Exports<'gun/sea/sha1'>;
}
declare module 'gun/sea/sha256.js' {
  declare module.exports: $Exports<'gun/sea/sha256'>;
}
declare module 'gun/sea/shim.js' {
  declare module.exports: $Exports<'gun/sea/shim'>;
}
declare module 'gun/sea/sign.js' {
  declare module.exports: $Exports<'gun/sea/sign'>;
}
declare module 'gun/sea/then.js' {
  declare module.exports: $Exports<'gun/sea/then'>;
}
declare module 'gun/sea/user.js' {
  declare module.exports: $Exports<'gun/sea/user'>;
}
declare module 'gun/sea/verify.js' {
  declare module.exports: $Exports<'gun/sea/verify'>;
}
declare module 'gun/sea/work.js' {
  declare module.exports: $Exports<'gun/sea/work'>;
}
declare module 'gun/src/adapters/localStorage.js' {
  declare module.exports: $Exports<'gun/src/adapters/localStorage'>;
}
declare module 'gun/src/adapters/mesh.js' {
  declare module.exports: $Exports<'gun/src/adapters/mesh'>;
}
declare module 'gun/src/adapters/websocket.js' {
  declare module.exports: $Exports<'gun/src/adapters/websocket'>;
}
declare module 'gun/src/ask.js' {
  declare module.exports: $Exports<'gun/src/ask'>;
}
declare module 'gun/src/back.js' {
  declare module.exports: $Exports<'gun/src/back'>;
}
declare module 'gun/src/chain.js' {
  declare module.exports: $Exports<'gun/src/chain'>;
}
declare module 'gun/src/dup.js' {
  declare module.exports: $Exports<'gun/src/dup'>;
}
declare module 'gun/src/get.js' {
  declare module.exports: $Exports<'gun/src/get'>;
}
declare module 'gun/src/graph.js' {
  declare module.exports: $Exports<'gun/src/graph'>;
}
declare module 'gun/src/HAM.js' {
  declare module.exports: $Exports<'gun/src/HAM'>;
}
declare module 'gun/src/index.js' {
  declare module.exports: $Exports<'gun/src/index'>;
}
declare module 'gun/src/map.js' {
  declare module.exports: $Exports<'gun/src/map'>;
}
declare module 'gun/src/node.js' {
  declare module.exports: $Exports<'gun/src/node'>;
}
declare module 'gun/src/on.js' {
  declare module.exports: $Exports<'gun/src/on'>;
}
declare module 'gun/src/onto.js' {
  declare module.exports: $Exports<'gun/src/onto'>;
}
declare module 'gun/src/polyfill/unbuild.js' {
  declare module.exports: $Exports<'gun/src/polyfill/unbuild'>;
}
declare module 'gun/src/put.js' {
  declare module.exports: $Exports<'gun/src/put'>;
}
declare module 'gun/src/root.js' {
  declare module.exports: $Exports<'gun/src/root'>;
}
declare module 'gun/src/set.js' {
  declare module.exports: $Exports<'gun/src/set'>;
}
declare module 'gun/src/state.js' {
  declare module.exports: $Exports<'gun/src/state'>;
}
declare module 'gun/src/type.js' {
  declare module.exports: $Exports<'gun/src/type'>;
}
declare module 'gun/src/val.js' {
  declare module.exports: $Exports<'gun/src/val'>;
}
declare module 'gun/test/abc.js' {
  declare module.exports: $Exports<'gun/test/abc'>;
}
declare module 'gun/test/axe/holy-grail.js' {
  declare module.exports: $Exports<'gun/test/axe/holy-grail'>;
}
declare module 'gun/test/common.js' {
  declare module.exports: $Exports<'gun/test/common'>;
}
declare module 'gun/test/expect.js' {
  declare module.exports: $Exports<'gun/test/expect'>;
}
declare module 'gun/test/https/test.js' {
  declare module.exports: $Exports<'gun/test/https/test'>;
}
declare module 'gun/test/index.js' {
  declare module.exports: $Exports<'gun/test/index'>;
}
declare module 'gun/test/json2.js' {
  declare module.exports: $Exports<'gun/test/json2'>;
}
declare module 'gun/test/mocha.js' {
  declare module.exports: $Exports<'gun/test/mocha'>;
}
declare module 'gun/test/old/all.js' {
  declare module.exports: $Exports<'gun/test/old/all'>;
}
declare module 'gun/test/old/interface.js' {
  declare module.exports: $Exports<'gun/test/old/interface'>;
}
declare module 'gun/test/old/performance.js' {
  declare module.exports: $Exports<'gun/test/old/performance'>;
}
declare module 'gun/test/old/server.js' {
  declare module.exports: $Exports<'gun/test/old/server'>;
}
declare module 'gun/test/old/set.js' {
  declare module.exports: $Exports<'gun/test/old/set'>;
}
declare module 'gun/test/old/shoot.js' {
  declare module.exports: $Exports<'gun/test/old/shoot'>;
}
declare module 'gun/test/old/shotgun.js' {
  declare module.exports: $Exports<'gun/test/old/shotgun'>;
}
declare module 'gun/test/old/tmp.js' {
  declare module.exports: $Exports<'gun/test/old/tmp'>;
}
declare module 'gun/test/panic/b2s2s2b.js' {
  declare module.exports: $Exports<'gun/test/panic/b2s2s2b'>;
}
declare module 'gun/test/panic/curl-server.js' {
  declare module.exports: $Exports<'gun/test/panic/curl-server'>;
}
declare module 'gun/test/panic/e2e/distributed.js' {
  declare module.exports: $Exports<'gun/test/panic/e2e/distributed'>;
}
declare module 'gun/test/panic/e2e/holy/grail.js' {
  declare module.exports: $Exports<'gun/test/panic/e2e/holy/grail'>;
}
declare module 'gun/test/panic/e2e/holy/gun-server.js' {
  declare module.exports: $Exports<'gun/test/panic/e2e/holy/gun-server'>;
}
declare module 'gun/test/panic/holy-grail.js' {
  declare module.exports: $Exports<'gun/test/panic/holy-grail'>;
}
declare module 'gun/test/panic/load.js' {
  declare module.exports: $Exports<'gun/test/panic/load'>;
}
declare module 'gun/test/panic/radisk.js' {
  declare module.exports: $Exports<'gun/test/panic/radisk'>;
}
declare module 'gun/test/panic/s2s-all-delayed-peer-add.js' {
  declare module.exports: $Exports<'gun/test/panic/s2s-all-delayed-peer-add'>;
}
declare module 'gun/test/panic/s2s-all.js' {
  declare module.exports: $Exports<'gun/test/panic/s2s-all'>;
}
declare module 'gun/test/panic/scale.js' {
  declare module.exports: $Exports<'gun/test/panic/scale'>;
}
declare module 'gun/test/panic/set.js' {
  declare module.exports: $Exports<'gun/test/panic/set'>;
}
declare module 'gun/test/panic/speak.js' {
  declare module.exports: $Exports<'gun/test/panic/speak'>;
}
declare module 'gun/test/panic/users.js' {
  declare module.exports: $Exports<'gun/test/panic/users'>;
}
declare module 'gun/test/panic/who.js' {
  declare module.exports: $Exports<'gun/test/panic/who'>;
}
declare module 'gun/test/ptsd/benchmark.js' {
  declare module.exports: $Exports<'gun/test/ptsd/benchmark'>;
}
declare module 'gun/test/ptsd/memdisk.js' {
  declare module.exports: $Exports<'gun/test/ptsd/memdisk'>;
}
declare module 'gun/test/ptsd/perf.js' {
  declare module.exports: $Exports<'gun/test/ptsd/perf'>;
}
declare module 'gun/test/ptsd/ptsd.js' {
  declare module.exports: $Exports<'gun/test/ptsd/ptsd'>;
}
declare module 'gun/test/ptsd/radix.js' {
  declare module.exports: $Exports<'gun/test/ptsd/radix'>;
}
declare module 'gun/test/ptsd/spam.js' {
  declare module.exports: $Exports<'gun/test/ptsd/spam'>;
}
declare module 'gun/test/ptsd/streampipe.js' {
  declare module.exports: $Exports<'gun/test/ptsd/streampipe'>;
}
declare module 'gun/test/rad/rad.js' {
  declare module.exports: $Exports<'gun/test/rad/rad'>;
}
declare module 'gun/test/radix.js' {
  declare module.exports: $Exports<'gun/test/radix'>;
}
declare module 'gun/test/sea/sea_old.js' {
  declare module.exports: $Exports<'gun/test/sea/sea_old'>;
}
declare module 'gun/test/sea/sea.js' {
  declare module.exports: $Exports<'gun/test/sea/sea'>;
}
declare module 'gun/test/server/http.js' {
  declare module.exports: $Exports<'gun/test/server/http'>;
}
declare module 'gun/test/server/node-client.js' {
  declare module.exports: $Exports<'gun/test/server/node-client'>;
}
declare module 'gun/test/server/node-write.js' {
  declare module.exports: $Exports<'gun/test/server/node-write'>;
}
declare module 'gun/test/tmp/bigsync.js' {
  declare module.exports: $Exports<'gun/test/tmp/bigsync'>;
}
declare module 'gun/test/tmp/mitra/client_to_server.js' {
  declare module.exports: $Exports<'gun/test/tmp/mitra/client_to_server'>;
}
declare module 'gun/test/tmp/mitra/gun_https2.js' {
  declare module.exports: $Exports<'gun/test/tmp/mitra/gun_https2'>;
}
declare module 'gun/test/tmp/seanode.js' {
  declare module.exports: $Exports<'gun/test/tmp/seanode'>;
}
