// flow-typed signature: 28a5d1828577d5808e0534c2c9927531
// flow-typed version: <<STUB>>/jest-resolve_v23.6.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-resolve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-resolve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-resolve/build/default_resolver' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/index' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/is_builtin_module' {
  declare module.exports: any;
}

declare module 'jest-resolve/build/node_modules_paths' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-resolve/build/default_resolver.js' {
  declare module.exports: $Exports<'jest-resolve/build/default_resolver'>;
}
declare module 'jest-resolve/build/index.js' {
  declare module.exports: $Exports<'jest-resolve/build/index'>;
}
declare module 'jest-resolve/build/is_builtin_module.js' {
  declare module.exports: $Exports<'jest-resolve/build/is_builtin_module'>;
}
declare module 'jest-resolve/build/node_modules_paths.js' {
  declare module.exports: $Exports<'jest-resolve/build/node_modules_paths'>;
}
