// flow-typed signature: d8818c9c4e9d1e04dcb23bbf376b3f10
// flow-typed version: <<STUB>>/loadjs_v^3.6.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loadjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loadjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loadjs/dist/loadjs' {
  declare module.exports: any;
}

declare module 'loadjs/dist/loadjs.min' {
  declare module.exports: any;
}

declare module 'loadjs/dist/loadjs.umd' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/example-error' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/file1' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/file2' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/file3' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/loadjs/loadjs' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/loadjs/loadjs.min' {
  declare module.exports: any;
}

declare module 'loadjs/examples/assets/log' {
  declare module.exports: any;
}

declare module 'loadjs/gulpfile' {
  declare module.exports: any;
}

declare module 'loadjs/src/loadjs' {
  declare module.exports: any;
}

declare module 'loadjs/test/assets/asyncfalse1' {
  declare module.exports: any;
}

declare module 'loadjs/test/assets/asyncfalse2' {
  declare module.exports: any;
}

declare module 'loadjs/test/assets/file1' {
  declare module.exports: any;
}

declare module 'loadjs/test/assets/file2' {
  declare module.exports: any;
}

declare module 'loadjs/test/assets/loadjs/loadjs' {
  declare module.exports: any;
}

declare module 'loadjs/test/assets/loadjs/loadjs.min' {
  declare module.exports: any;
}

declare module 'loadjs/test/tests' {
  declare module.exports: any;
}

declare module 'loadjs/test/vendor/chai-4.1.2' {
  declare module.exports: any;
}

declare module 'loadjs/test/vendor/mocha-4.1.0/mocha' {
  declare module.exports: any;
}

declare module 'loadjs/umd-templates/UMD' {
  declare module.exports: any;
}

declare module 'loadjs/umd-templates/web' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loadjs/dist/loadjs.js' {
  declare module.exports: $Exports<'loadjs/dist/loadjs'>;
}
declare module 'loadjs/dist/loadjs.min.js' {
  declare module.exports: $Exports<'loadjs/dist/loadjs.min'>;
}
declare module 'loadjs/dist/loadjs.umd.js' {
  declare module.exports: $Exports<'loadjs/dist/loadjs.umd'>;
}
declare module 'loadjs/examples/assets/example-error.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/example-error'>;
}
declare module 'loadjs/examples/assets/file1.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/file1'>;
}
declare module 'loadjs/examples/assets/file2.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/file2'>;
}
declare module 'loadjs/examples/assets/file3.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/file3'>;
}
declare module 'loadjs/examples/assets/loadjs/loadjs.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/loadjs/loadjs'>;
}
declare module 'loadjs/examples/assets/loadjs/loadjs.min.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/loadjs/loadjs.min'>;
}
declare module 'loadjs/examples/assets/log.js' {
  declare module.exports: $Exports<'loadjs/examples/assets/log'>;
}
declare module 'loadjs/gulpfile.js' {
  declare module.exports: $Exports<'loadjs/gulpfile'>;
}
declare module 'loadjs/src/loadjs.js' {
  declare module.exports: $Exports<'loadjs/src/loadjs'>;
}
declare module 'loadjs/test/assets/asyncfalse1.js' {
  declare module.exports: $Exports<'loadjs/test/assets/asyncfalse1'>;
}
declare module 'loadjs/test/assets/asyncfalse2.js' {
  declare module.exports: $Exports<'loadjs/test/assets/asyncfalse2'>;
}
declare module 'loadjs/test/assets/file1.js' {
  declare module.exports: $Exports<'loadjs/test/assets/file1'>;
}
declare module 'loadjs/test/assets/file2.js' {
  declare module.exports: $Exports<'loadjs/test/assets/file2'>;
}
declare module 'loadjs/test/assets/loadjs/loadjs.js' {
  declare module.exports: $Exports<'loadjs/test/assets/loadjs/loadjs'>;
}
declare module 'loadjs/test/assets/loadjs/loadjs.min.js' {
  declare module.exports: $Exports<'loadjs/test/assets/loadjs/loadjs.min'>;
}
declare module 'loadjs/test/tests.js' {
  declare module.exports: $Exports<'loadjs/test/tests'>;
}
declare module 'loadjs/test/vendor/chai-4.1.2.js' {
  declare module.exports: $Exports<'loadjs/test/vendor/chai-4.1.2'>;
}
declare module 'loadjs/test/vendor/mocha-4.1.0/mocha.js' {
  declare module.exports: $Exports<'loadjs/test/vendor/mocha-4.1.0/mocha'>;
}
declare module 'loadjs/umd-templates/UMD.js' {
  declare module.exports: $Exports<'loadjs/umd-templates/UMD'>;
}
declare module 'loadjs/umd-templates/web.js' {
  declare module.exports: $Exports<'loadjs/umd-templates/web'>;
}
