// flow-typed signature: 52a08f5747012355c1eff22d6d9cdfec
// flow-typed version: <<STUB>>/mnid_v^0.1.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mnid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mnid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mnid/lib/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'mnid/lib/index' {
  declare module.exports: any;
}

declare module 'mnid/src/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'mnid/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mnid/lib/__tests__/index-test.js' {
  declare module.exports: $Exports<'mnid/lib/__tests__/index-test'>;
}
declare module 'mnid/lib/index.js' {
  declare module.exports: $Exports<'mnid/lib/index'>;
}
declare module 'mnid/src/__tests__/index-test.js' {
  declare module.exports: $Exports<'mnid/src/__tests__/index-test'>;
}
declare module 'mnid/src/index.js' {
  declare module.exports: $Exports<'mnid/src/index'>;
}
