// flow-typed signature: 583a165efa596ef9f30cf49c2f22e535
// flow-typed version: <<STUB>>/mobile-device-detect_v^0.2.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobile-device-detect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobile-device-detect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobile-device-detect/dist/index' {
  declare module.exports: any;
}

declare module 'mobile-device-detect/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobile-device-detect/dist/index.js' {
  declare module.exports: $Exports<'mobile-device-detect/dist/index'>;
}
declare module 'mobile-device-detect/webpack.config.js' {
  declare module.exports: $Exports<'mobile-device-detect/webpack.config'>;
}
