// flow-typed signature: 82a8f09d7888811a538f905c6e4eaf2a
// flow-typed version: <<STUB>>/node-webcrypto-ossl_v^1.0.42/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-webcrypto-ossl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-webcrypto-ossl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-webcrypto-ossl/buildjs/crypto' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/crypto/aes' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/crypto/ec' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/crypto/hmac' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/crypto/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/crypto/rsa' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/index' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/key_storage' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/key' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/native' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/subtle' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/buildjs/webcrypto' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/aes' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/config' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/crypto' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/digest' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/ec' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/helper' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/hmac' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/key_storage' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/native_hmac' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/native' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/native/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/rsa' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/vectors/aes_ctr' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/vectors/aes_kw' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/vectors/ec_secp256k1' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/vectors/hmac' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/vectors/pbkdf2' {
  declare module.exports: any;
}

declare module 'node-webcrypto-ossl/test/vectors/rsa_pss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-webcrypto-ossl/buildjs/crypto.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/crypto'>;
}
declare module 'node-webcrypto-ossl/buildjs/crypto/aes.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/crypto/aes'>;
}
declare module 'node-webcrypto-ossl/buildjs/crypto/ec.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/crypto/ec'>;
}
declare module 'node-webcrypto-ossl/buildjs/crypto/hmac.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/crypto/hmac'>;
}
declare module 'node-webcrypto-ossl/buildjs/crypto/pbkdf2.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/crypto/pbkdf2'>;
}
declare module 'node-webcrypto-ossl/buildjs/crypto/rsa.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/crypto/rsa'>;
}
declare module 'node-webcrypto-ossl/buildjs/index.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/index'>;
}
declare module 'node-webcrypto-ossl/buildjs/key_storage.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/key_storage'>;
}
declare module 'node-webcrypto-ossl/buildjs/key.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/key'>;
}
declare module 'node-webcrypto-ossl/buildjs/native.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/native'>;
}
declare module 'node-webcrypto-ossl/buildjs/subtle.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/subtle'>;
}
declare module 'node-webcrypto-ossl/buildjs/webcrypto.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/buildjs/webcrypto'>;
}
declare module 'node-webcrypto-ossl/test/aes.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/aes'>;
}
declare module 'node-webcrypto-ossl/test/config.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/config'>;
}
declare module 'node-webcrypto-ossl/test/crypto.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/crypto'>;
}
declare module 'node-webcrypto-ossl/test/digest.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/digest'>;
}
declare module 'node-webcrypto-ossl/test/ec.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/ec'>;
}
declare module 'node-webcrypto-ossl/test/helper.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/helper'>;
}
declare module 'node-webcrypto-ossl/test/hmac.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/hmac'>;
}
declare module 'node-webcrypto-ossl/test/key_storage.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/key_storage'>;
}
declare module 'node-webcrypto-ossl/test/native_hmac.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/native_hmac'>;
}
declare module 'node-webcrypto-ossl/test/native.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/native'>;
}
declare module 'node-webcrypto-ossl/test/native/pbkdf2.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/native/pbkdf2'>;
}
declare module 'node-webcrypto-ossl/test/pbkdf2.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/pbkdf2'>;
}
declare module 'node-webcrypto-ossl/test/rsa.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/rsa'>;
}
declare module 'node-webcrypto-ossl/test/vectors/aes_ctr.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/vectors/aes_ctr'>;
}
declare module 'node-webcrypto-ossl/test/vectors/aes_kw.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/vectors/aes_kw'>;
}
declare module 'node-webcrypto-ossl/test/vectors/ec_secp256k1.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/vectors/ec_secp256k1'>;
}
declare module 'node-webcrypto-ossl/test/vectors/hmac.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/vectors/hmac'>;
}
declare module 'node-webcrypto-ossl/test/vectors/pbkdf2.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/vectors/pbkdf2'>;
}
declare module 'node-webcrypto-ossl/test/vectors/rsa_pss.js' {
  declare module.exports: $Exports<'node-webcrypto-ossl/test/vectors/rsa_pss'>;
}
