// flow-typed signature: fa14629cc6b6138bb789622c398f21d1
// flow-typed version: <<STUB>>/pino_v^5.12.6/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pino'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pino' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pino/bin' {
  declare module.exports: any;
}

declare module 'pino/browser' {
  declare module.exports: any;
}

declare module 'pino/example' {
  declare module.exports: any;
}

declare module 'pino/lib/levels' {
  declare module.exports: any;
}

declare module 'pino/lib/meta' {
  declare module.exports: any;
}

declare module 'pino/lib/proto' {
  declare module.exports: any;
}

declare module 'pino/lib/redaction' {
  declare module.exports: any;
}

declare module 'pino/lib/symbols' {
  declare module.exports: any;
}

declare module 'pino/lib/time' {
  declare module.exports: any;
}

declare module 'pino/lib/tools' {
  declare module.exports: any;
}

declare module 'pino/pino' {
  declare module.exports: any;
}

declare module 'pino/test/basic.test' {
  declare module.exports: any;
}

declare module 'pino/test/broken-pipe.test' {
  declare module.exports: any;
}

declare module 'pino/test/browser-levels.test' {
  declare module.exports: any;
}

declare module 'pino/test/browser-serializers.test' {
  declare module.exports: any;
}

declare module 'pino/test/browser-transmit.test' {
  declare module.exports: any;
}

declare module 'pino/test/browser.test' {
  declare module.exports: any;
}

declare module 'pino/test/crlf.test' {
  declare module.exports: any;
}

declare module 'pino/test/custom-levels.test' {
  declare module.exports: any;
}

declare module 'pino/test/error.test' {
  declare module.exports: any;
}

declare module 'pino/test/escaping.test' {
  declare module.exports: any;
}

declare module 'pino/test/exit.test' {
  declare module.exports: any;
}

declare module 'pino/test/extreme.test' {
  declare module.exports: any;
}

declare module 'pino/test/final.test' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/broken-pipe/basic' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/broken-pipe/destination' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/broken-pipe/extreme' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/destination-exit' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme-child' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme-exit' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme-flush-exit' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/extreme' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/basic' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/child' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/custom-time' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/dateformat' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/error-props' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/error' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/final-no-log-before' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/final-return' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/final' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/level-first' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/no-time' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/obj-msg-prop' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/pretty-factory' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/redact' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/serializers' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/pretty/skipped-output' {
  declare module.exports: any;
}

declare module 'pino/test/fixtures/stdout-hack-protection' {
  declare module.exports: any;
}

declare module 'pino/test/helper' {
  declare module.exports: any;
}

declare module 'pino/test/http.test' {
  declare module.exports: any;
}

declare module 'pino/test/is-level-enabled.test' {
  declare module.exports: any;
}

declare module 'pino/test/levels.test' {
  declare module.exports: any;
}

declare module 'pino/test/metadata.test' {
  declare module.exports: any;
}

declare module 'pino/test/pretty.test' {
  declare module.exports: any;
}

declare module 'pino/test/redact.test' {
  declare module.exports: any;
}

declare module 'pino/test/serializers.test' {
  declare module.exports: any;
}

declare module 'pino/test/stdout-protection.test' {
  declare module.exports: any;
}

declare module 'pino/test/timestamp.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pino/bin.js' {
  declare module.exports: $Exports<'pino/bin'>;
}
declare module 'pino/browser.js' {
  declare module.exports: $Exports<'pino/browser'>;
}
declare module 'pino/example.js' {
  declare module.exports: $Exports<'pino/example'>;
}
declare module 'pino/lib/levels.js' {
  declare module.exports: $Exports<'pino/lib/levels'>;
}
declare module 'pino/lib/meta.js' {
  declare module.exports: $Exports<'pino/lib/meta'>;
}
declare module 'pino/lib/proto.js' {
  declare module.exports: $Exports<'pino/lib/proto'>;
}
declare module 'pino/lib/redaction.js' {
  declare module.exports: $Exports<'pino/lib/redaction'>;
}
declare module 'pino/lib/symbols.js' {
  declare module.exports: $Exports<'pino/lib/symbols'>;
}
declare module 'pino/lib/time.js' {
  declare module.exports: $Exports<'pino/lib/time'>;
}
declare module 'pino/lib/tools.js' {
  declare module.exports: $Exports<'pino/lib/tools'>;
}
declare module 'pino/pino.js' {
  declare module.exports: $Exports<'pino/pino'>;
}
declare module 'pino/test/basic.test.js' {
  declare module.exports: $Exports<'pino/test/basic.test'>;
}
declare module 'pino/test/broken-pipe.test.js' {
  declare module.exports: $Exports<'pino/test/broken-pipe.test'>;
}
declare module 'pino/test/browser-levels.test.js' {
  declare module.exports: $Exports<'pino/test/browser-levels.test'>;
}
declare module 'pino/test/browser-serializers.test.js' {
  declare module.exports: $Exports<'pino/test/browser-serializers.test'>;
}
declare module 'pino/test/browser-transmit.test.js' {
  declare module.exports: $Exports<'pino/test/browser-transmit.test'>;
}
declare module 'pino/test/browser.test.js' {
  declare module.exports: $Exports<'pino/test/browser.test'>;
}
declare module 'pino/test/crlf.test.js' {
  declare module.exports: $Exports<'pino/test/crlf.test'>;
}
declare module 'pino/test/custom-levels.test.js' {
  declare module.exports: $Exports<'pino/test/custom-levels.test'>;
}
declare module 'pino/test/error.test.js' {
  declare module.exports: $Exports<'pino/test/error.test'>;
}
declare module 'pino/test/escaping.test.js' {
  declare module.exports: $Exports<'pino/test/escaping.test'>;
}
declare module 'pino/test/exit.test.js' {
  declare module.exports: $Exports<'pino/test/exit.test'>;
}
declare module 'pino/test/extreme.test.js' {
  declare module.exports: $Exports<'pino/test/extreme.test'>;
}
declare module 'pino/test/final.test.js' {
  declare module.exports: $Exports<'pino/test/final.test'>;
}
declare module 'pino/test/fixtures/broken-pipe/basic.js' {
  declare module.exports: $Exports<'pino/test/fixtures/broken-pipe/basic'>;
}
declare module 'pino/test/fixtures/broken-pipe/destination.js' {
  declare module.exports: $Exports<'pino/test/fixtures/broken-pipe/destination'>;
}
declare module 'pino/test/fixtures/broken-pipe/extreme.js' {
  declare module.exports: $Exports<'pino/test/fixtures/broken-pipe/extreme'>;
}
declare module 'pino/test/fixtures/destination-exit.js' {
  declare module.exports: $Exports<'pino/test/fixtures/destination-exit'>;
}
declare module 'pino/test/fixtures/extreme-child.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme-child'>;
}
declare module 'pino/test/fixtures/extreme-exit.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme-exit'>;
}
declare module 'pino/test/fixtures/extreme-flush-exit.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme-flush-exit'>;
}
declare module 'pino/test/fixtures/extreme.js' {
  declare module.exports: $Exports<'pino/test/fixtures/extreme'>;
}
declare module 'pino/test/fixtures/pretty/basic.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/basic'>;
}
declare module 'pino/test/fixtures/pretty/child.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/child'>;
}
declare module 'pino/test/fixtures/pretty/custom-time.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/custom-time'>;
}
declare module 'pino/test/fixtures/pretty/dateformat.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/dateformat'>;
}
declare module 'pino/test/fixtures/pretty/error-props.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/error-props'>;
}
declare module 'pino/test/fixtures/pretty/error.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/error'>;
}
declare module 'pino/test/fixtures/pretty/final-no-log-before.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/final-no-log-before'>;
}
declare module 'pino/test/fixtures/pretty/final-return.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/final-return'>;
}
declare module 'pino/test/fixtures/pretty/final.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/final'>;
}
declare module 'pino/test/fixtures/pretty/level-first.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/level-first'>;
}
declare module 'pino/test/fixtures/pretty/no-time.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/no-time'>;
}
declare module 'pino/test/fixtures/pretty/obj-msg-prop.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/obj-msg-prop'>;
}
declare module 'pino/test/fixtures/pretty/pretty-factory.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/pretty-factory'>;
}
declare module 'pino/test/fixtures/pretty/redact.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/redact'>;
}
declare module 'pino/test/fixtures/pretty/serializers.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/serializers'>;
}
declare module 'pino/test/fixtures/pretty/skipped-output.js' {
  declare module.exports: $Exports<'pino/test/fixtures/pretty/skipped-output'>;
}
declare module 'pino/test/fixtures/stdout-hack-protection.js' {
  declare module.exports: $Exports<'pino/test/fixtures/stdout-hack-protection'>;
}
declare module 'pino/test/helper.js' {
  declare module.exports: $Exports<'pino/test/helper'>;
}
declare module 'pino/test/http.test.js' {
  declare module.exports: $Exports<'pino/test/http.test'>;
}
declare module 'pino/test/is-level-enabled.test.js' {
  declare module.exports: $Exports<'pino/test/is-level-enabled.test'>;
}
declare module 'pino/test/levels.test.js' {
  declare module.exports: $Exports<'pino/test/levels.test'>;
}
declare module 'pino/test/metadata.test.js' {
  declare module.exports: $Exports<'pino/test/metadata.test'>;
}
declare module 'pino/test/pretty.test.js' {
  declare module.exports: $Exports<'pino/test/pretty.test'>;
}
declare module 'pino/test/redact.test.js' {
  declare module.exports: $Exports<'pino/test/redact.test'>;
}
declare module 'pino/test/serializers.test.js' {
  declare module.exports: $Exports<'pino/test/serializers.test'>;
}
declare module 'pino/test/stdout-protection.test.js' {
  declare module.exports: $Exports<'pino/test/stdout-protection.test'>;
}
declare module 'pino/test/timestamp.test.js' {
  declare module.exports: $Exports<'pino/test/timestamp.test'>;
}
