// flow-typed signature: 8d0c78c41e4172d6989c8aac192a3d24
// flow-typed version: <<STUB>>/react-native-side-menu-gooddapp_v2.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-side-menu-gooddapp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-side-menu-gooddapp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-side-menu-gooddapp/build/index' {
  declare module.exports: any;
}

declare module 'react-native-side-menu-gooddapp/build/styles' {
  declare module.exports: any;
}

declare module 'react-native-side-menu-gooddapp/libdefs' {
  declare module.exports: any;
}

declare module 'react-native-side-menu-gooddapp/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-side-menu-gooddapp/build/index.js' {
  declare module.exports: $Exports<'react-native-side-menu-gooddapp/build/index'>;
}
declare module 'react-native-side-menu-gooddapp/build/styles.js' {
  declare module.exports: $Exports<'react-native-side-menu-gooddapp/build/styles'>;
}
declare module 'react-native-side-menu-gooddapp/index' {
  declare module.exports: $Exports<'react-native-side-menu-gooddapp'>;
}
declare module 'react-native-side-menu-gooddapp/index.js' {
  declare module.exports: $Exports<'react-native-side-menu-gooddapp'>;
}
declare module 'react-native-side-menu-gooddapp/libdefs.js' {
  declare module.exports: $Exports<'react-native-side-menu-gooddapp/libdefs'>;
}
declare module 'react-native-side-menu-gooddapp/styles.js' {
  declare module.exports: $Exports<'react-native-side-menu-gooddapp/styles'>;
}
