// flow-typed signature: 4d2f5becfb62a4ed548025f644d84cd5
// flow-typed version: <<STUB>>/react-native-web-webview_v^0.2.8/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-web-webview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-web-webview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-web-webview/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-web-webview/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-web-webview/dist/index.js' {
  declare module.exports: $Exports<'react-native-web-webview/dist/index'>;
}
declare module 'react-native-web-webview/src/index.js' {
  declare module.exports: $Exports<'react-native-web-webview/src/index'>;
}
