// flow-typed signature: 2604aecd572973a8e3f4e5195d0c6578
// flow-typed version: <<STUB>>/react-otp-input_v^0.2.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-otp-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-otp-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-otp-input/demo/bundle' {
  declare module.exports: any;
}

declare module 'react-otp-input/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-otp-input/demo/bundle.js' {
  declare module.exports: $Exports<'react-otp-input/demo/bundle'>;
}
declare module 'react-otp-input/lib/index.js' {
  declare module.exports: $Exports<'react-otp-input/lib/index'>;
}
