// flow-typed signature: dbfeace875f35fc6ed089888f787f8ac
// flow-typed version: <<STUB>>/react-native-paper_v^2.11.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-paper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-paper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-paper/babel' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/babel/__fixtures__/rewrite-imports/code' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/babel/__fixtures__/rewrite-imports/output' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/babel/index' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ActivityIndicator' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Appbar/Appbar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Appbar/AppbarAction' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Appbar/AppbarBackAction' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Appbar/AppbarContent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Appbar/AppbarHeader' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Avatar/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Avatar/AvatarIcon' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Avatar/AvatarImage' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Avatar/AvatarText' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Badge' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Banner' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/BottomNavigation' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Button' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/Card' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardActions' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardContent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardCover' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Card/CardTitle' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Checkbox' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/CheckboxAndroid' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/CheckboxIOS' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Chip' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/CrossFadeIcon' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DataTable/DataTable' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DataTable/DataTableCell' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DataTable/DataTableHeader' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DataTable/DataTablePagination' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DataTable/DataTableRow' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/DataTable/DataTableTitle' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/Dialog' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogActions' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogContent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogScrollArea' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Dialog/DialogTitle' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Divider' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Drawer/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Drawer/DrawerItem' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Drawer/DrawerSection' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/FAB/FAB' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/FAB/FABGroup' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/HelperText' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Icon' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/IconButton' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/List/List' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/List/ListAccordion' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/List/ListIcon' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/List/ListItem' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/List/ListSection' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Modal' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/Portal' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/PortalConsumer' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/PortalHost' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Portal/PortalManager' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.android' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.ios' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.macos' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.windows' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/RadioButton' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/RadioButtonAndroid' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/RadioButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/RadioButtonIOS' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Searchbar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Snackbar' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Surface' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Switch' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/TextInput' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ToggleButton/ToggleButton' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/ToggleButton/ToggleButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/TouchableRipple/index' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/TouchableRipple/index.native' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Caption' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Headline' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Paragraph' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/StyledText' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Subheading' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Text' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/components/Typography/Title' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/core/Provider' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/core/theming' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/index' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/colors' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/DarkTheme' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/DefaultTheme' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/fonts' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/styles/shadow' {
  declare module.exports: any;
}

declare module 'react-native-paper/src/types' {
  declare module.exports: any;
}

declare module 'react-native-paper/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-paper/babel.js' {
  declare module.exports: $Exports<'react-native-paper/babel'>;
}
declare module 'react-native-paper/src/babel/__fixtures__/rewrite-imports/code.js' {
  declare module.exports: $Exports<'react-native-paper/src/babel/__fixtures__/rewrite-imports/code'>;
}
declare module 'react-native-paper/src/babel/__fixtures__/rewrite-imports/output.js' {
  declare module.exports: $Exports<'react-native-paper/src/babel/__fixtures__/rewrite-imports/output'>;
}
declare module 'react-native-paper/src/babel/index.js' {
  declare module.exports: $Exports<'react-native-paper/src/babel/index'>;
}
declare module 'react-native-paper/src/components/ActivityIndicator.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ActivityIndicator'>;
}
declare module 'react-native-paper/src/components/Appbar/Appbar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Appbar/Appbar'>;
}
declare module 'react-native-paper/src/components/Appbar/AppbarAction.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Appbar/AppbarAction'>;
}
declare module 'react-native-paper/src/components/Appbar/AppbarBackAction.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Appbar/AppbarBackAction'>;
}
declare module 'react-native-paper/src/components/Appbar/AppbarContent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Appbar/AppbarContent'>;
}
declare module 'react-native-paper/src/components/Appbar/AppbarHeader.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Appbar/AppbarHeader'>;
}
declare module 'react-native-paper/src/components/Avatar/Avatar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Avatar/Avatar'>;
}
declare module 'react-native-paper/src/components/Avatar/AvatarIcon.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Avatar/AvatarIcon'>;
}
declare module 'react-native-paper/src/components/Avatar/AvatarImage.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Avatar/AvatarImage'>;
}
declare module 'react-native-paper/src/components/Avatar/AvatarText.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Avatar/AvatarText'>;
}
declare module 'react-native-paper/src/components/Badge.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Badge'>;
}
declare module 'react-native-paper/src/components/Banner.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Banner'>;
}
declare module 'react-native-paper/src/components/BottomNavigation.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/BottomNavigation'>;
}
declare module 'react-native-paper/src/components/Button.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Button'>;
}
declare module 'react-native-paper/src/components/Card/Card.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/Card'>;
}
declare module 'react-native-paper/src/components/Card/CardActions.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardActions'>;
}
declare module 'react-native-paper/src/components/Card/CardContent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardContent'>;
}
declare module 'react-native-paper/src/components/Card/CardCover.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardCover'>;
}
declare module 'react-native-paper/src/components/Card/CardTitle.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Card/CardTitle'>;
}
declare module 'react-native-paper/src/components/Checkbox.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Checkbox'>;
}
declare module 'react-native-paper/src/components/CheckboxAndroid.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/CheckboxAndroid'>;
}
declare module 'react-native-paper/src/components/CheckboxIOS.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/CheckboxIOS'>;
}
declare module 'react-native-paper/src/components/Chip.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Chip'>;
}
declare module 'react-native-paper/src/components/CrossFadeIcon.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/CrossFadeIcon'>;
}
declare module 'react-native-paper/src/components/DataTable/DataTable.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DataTable/DataTable'>;
}
declare module 'react-native-paper/src/components/DataTable/DataTableCell.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DataTable/DataTableCell'>;
}
declare module 'react-native-paper/src/components/DataTable/DataTableHeader.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DataTable/DataTableHeader'>;
}
declare module 'react-native-paper/src/components/DataTable/DataTablePagination.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DataTable/DataTablePagination'>;
}
declare module 'react-native-paper/src/components/DataTable/DataTableRow.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DataTable/DataTableRow'>;
}
declare module 'react-native-paper/src/components/DataTable/DataTableTitle.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/DataTable/DataTableTitle'>;
}
declare module 'react-native-paper/src/components/Dialog/Dialog.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/Dialog'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogActions.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogActions'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogContent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogContent'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogScrollArea.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogScrollArea'>;
}
declare module 'react-native-paper/src/components/Dialog/DialogTitle.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Dialog/DialogTitle'>;
}
declare module 'react-native-paper/src/components/Divider.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Divider'>;
}
declare module 'react-native-paper/src/components/Drawer/Drawer.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Drawer/Drawer'>;
}
declare module 'react-native-paper/src/components/Drawer/DrawerItem.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Drawer/DrawerItem'>;
}
declare module 'react-native-paper/src/components/Drawer/DrawerSection.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Drawer/DrawerSection'>;
}
declare module 'react-native-paper/src/components/FAB/FAB.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/FAB/FAB'>;
}
declare module 'react-native-paper/src/components/FAB/FABGroup.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/FAB/FABGroup'>;
}
declare module 'react-native-paper/src/components/HelperText.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/HelperText'>;
}
declare module 'react-native-paper/src/components/Icon.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Icon'>;
}
declare module 'react-native-paper/src/components/IconButton.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/IconButton'>;
}
declare module 'react-native-paper/src/components/List/List.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/List/List'>;
}
declare module 'react-native-paper/src/components/List/ListAccordion.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/List/ListAccordion'>;
}
declare module 'react-native-paper/src/components/List/ListIcon.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/List/ListIcon'>;
}
declare module 'react-native-paper/src/components/List/ListItem.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/List/ListItem'>;
}
declare module 'react-native-paper/src/components/List/ListSection.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/List/ListSection'>;
}
declare module 'react-native-paper/src/components/Modal.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Modal'>;
}
declare module 'react-native-paper/src/components/Portal/Portal.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/Portal'>;
}
declare module 'react-native-paper/src/components/Portal/PortalConsumer.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/PortalConsumer'>;
}
declare module 'react-native-paper/src/components/Portal/PortalHost.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/PortalHost'>;
}
declare module 'react-native-paper/src/components/Portal/PortalManager.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Portal/PortalManager'>;
}
declare module 'react-native-paper/src/components/ProgressBar/ProgressBar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar/ProgressBar'>;
}
declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.android.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar/ProgressBarComponent.android'>;
}
declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.ios.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar/ProgressBarComponent.ios'>;
}
declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar/ProgressBarComponent'>;
}
declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.macos.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar/ProgressBarComponent.macos'>;
}
declare module 'react-native-paper/src/components/ProgressBar/ProgressBarComponent.windows.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ProgressBar/ProgressBarComponent.windows'>;
}
declare module 'react-native-paper/src/components/RadioButton.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/RadioButton'>;
}
declare module 'react-native-paper/src/components/RadioButtonAndroid.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/RadioButtonAndroid'>;
}
declare module 'react-native-paper/src/components/RadioButtonGroup.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/RadioButtonGroup'>;
}
declare module 'react-native-paper/src/components/RadioButtonIOS.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/RadioButtonIOS'>;
}
declare module 'react-native-paper/src/components/Searchbar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Searchbar'>;
}
declare module 'react-native-paper/src/components/Snackbar.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Snackbar'>;
}
declare module 'react-native-paper/src/components/Surface.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Surface'>;
}
declare module 'react-native-paper/src/components/Switch.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Switch'>;
}
declare module 'react-native-paper/src/components/TextInput.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/TextInput'>;
}
declare module 'react-native-paper/src/components/ToggleButton/ToggleButton.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ToggleButton/ToggleButton'>;
}
declare module 'react-native-paper/src/components/ToggleButton/ToggleButtonGroup.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/ToggleButton/ToggleButtonGroup'>;
}
declare module 'react-native-paper/src/components/TouchableRipple/index.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/TouchableRipple/index'>;
}
declare module 'react-native-paper/src/components/TouchableRipple/index.native.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/TouchableRipple/index.native'>;
}
declare module 'react-native-paper/src/components/Typography/Caption.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Caption'>;
}
declare module 'react-native-paper/src/components/Typography/Headline.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Headline'>;
}
declare module 'react-native-paper/src/components/Typography/Paragraph.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Paragraph'>;
}
declare module 'react-native-paper/src/components/Typography/StyledText.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/StyledText'>;
}
declare module 'react-native-paper/src/components/Typography/Subheading.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Subheading'>;
}
declare module 'react-native-paper/src/components/Typography/Text.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Text'>;
}
declare module 'react-native-paper/src/components/Typography/Title.js' {
  declare module.exports: $Exports<'react-native-paper/src/components/Typography/Title'>;
}
declare module 'react-native-paper/src/core/Provider.js' {
  declare module.exports: $Exports<'react-native-paper/src/core/Provider'>;
}
declare module 'react-native-paper/src/core/theming.js' {
  declare module.exports: $Exports<'react-native-paper/src/core/theming'>;
}
declare module 'react-native-paper/src/index.js' {
  declare module.exports: $Exports<'react-native-paper/src/index'>;
}
declare module 'react-native-paper/src/styles/colors.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/colors'>;
}
declare module 'react-native-paper/src/styles/DarkTheme.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/DarkTheme'>;
}
declare module 'react-native-paper/src/styles/DefaultTheme.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/DefaultTheme'>;
}
declare module 'react-native-paper/src/styles/fonts.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/fonts'>;
}
declare module 'react-native-paper/src/styles/shadow.js' {
  declare module.exports: $Exports<'react-native-paper/src/styles/shadow'>;
}
declare module 'react-native-paper/src/types.js' {
  declare module.exports: $Exports<'react-native-paper/src/types'>;
}
declare module 'react-native-paper/types.js' {
  declare module.exports: $Exports<'react-native-paper/types'>;
}
