// flow-typed signature: 6e877627bf888c4e81301ecea6b034e5
// flow-typed version: <<STUB>>/react-native-qrcode-scanner_v^1.1.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-qrcode-scanner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-qrcode-scanner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-qrcode-scanner/examples/default' {
  declare module.exports: any;
}

declare module 'react-native-qrcode-scanner/examples/fullScreen.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-qrcode-scanner/examples/default.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner/examples/default'>;
}
declare module 'react-native-qrcode-scanner/examples/fullScreen.ios.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner/examples/fullScreen.ios'>;
}
declare module 'react-native-qrcode-scanner/index' {
  declare module.exports: $Exports<'react-native-qrcode-scanner'>;
}
declare module 'react-native-qrcode-scanner/index.js' {
  declare module.exports: $Exports<'react-native-qrcode-scanner'>;
}
