// flow-typed signature: cdcff5231c9f2036a7278f73780f9ce4
// flow-typed version: <<STUB>>/react-native-masked-text_v^1.11.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-masked-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-masked-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-masked-text/__tests__/mask/cel-phone.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/cnpj.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/cpf.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/credit-card.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/custom.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/datetime.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/money.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/only-numbers.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/__tests__/mask/zip-code.mask.test' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/base-text-component' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/internal-dependencies/vanilla-masker' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/mask-resolver' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/mask-service' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/_base.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/cel-phone.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/cnpj.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/cpf.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/credit-card.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/custom.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/datetime.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/index' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/money.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/only-numbers.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/masks/zip-code.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/text-input-mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/lib/text-mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/dist/rnmt' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/base-text-component' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/internal-dependencies/vanilla-masker' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/mask-resolver' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/mask-service' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/_base.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/cel-phone.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/cnpj.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/cpf.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/credit-card.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/custom.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/datetime.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/index' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/money.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/only-numbers.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/masks/zip-code.mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/text-input-mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/lib/text-mask' {
  declare module.exports: any;
}

declare module 'react-native-masked-text/rnmt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-masked-text/__tests__/mask/cel-phone.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/cel-phone.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/cnpj.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/cnpj.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/cpf.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/cpf.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/credit-card.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/credit-card.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/custom.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/custom.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/datetime.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/datetime.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/money.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/money.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/only-numbers.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/only-numbers.mask.test'>;
}
declare module 'react-native-masked-text/__tests__/mask/zip-code.mask.test.js' {
  declare module.exports: $Exports<'react-native-masked-text/__tests__/mask/zip-code.mask.test'>;
}
declare module 'react-native-masked-text/dist/lib/base-text-component.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/base-text-component'>;
}
declare module 'react-native-masked-text/dist/lib/internal-dependencies/vanilla-masker.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/internal-dependencies/vanilla-masker'>;
}
declare module 'react-native-masked-text/dist/lib/mask-resolver.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/mask-resolver'>;
}
declare module 'react-native-masked-text/dist/lib/mask-service.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/mask-service'>;
}
declare module 'react-native-masked-text/dist/lib/masks/_base.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/_base.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/cel-phone.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/cel-phone.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/cnpj.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/cnpj.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/cpf.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/cpf.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/credit-card.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/credit-card.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/custom.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/custom.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/datetime.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/datetime.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/index.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/index'>;
}
declare module 'react-native-masked-text/dist/lib/masks/money.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/money.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/only-numbers.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/only-numbers.mask'>;
}
declare module 'react-native-masked-text/dist/lib/masks/zip-code.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/masks/zip-code.mask'>;
}
declare module 'react-native-masked-text/dist/lib/text-input-mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/text-input-mask'>;
}
declare module 'react-native-masked-text/dist/lib/text-mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/lib/text-mask'>;
}
declare module 'react-native-masked-text/dist/rnmt.js' {
  declare module.exports: $Exports<'react-native-masked-text/dist/rnmt'>;
}
declare module 'react-native-masked-text/lib/base-text-component.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/base-text-component'>;
}
declare module 'react-native-masked-text/lib/internal-dependencies/vanilla-masker.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/internal-dependencies/vanilla-masker'>;
}
declare module 'react-native-masked-text/lib/mask-resolver.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/mask-resolver'>;
}
declare module 'react-native-masked-text/lib/mask-service.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/mask-service'>;
}
declare module 'react-native-masked-text/lib/masks/_base.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/_base.mask'>;
}
declare module 'react-native-masked-text/lib/masks/cel-phone.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/cel-phone.mask'>;
}
declare module 'react-native-masked-text/lib/masks/cnpj.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/cnpj.mask'>;
}
declare module 'react-native-masked-text/lib/masks/cpf.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/cpf.mask'>;
}
declare module 'react-native-masked-text/lib/masks/credit-card.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/credit-card.mask'>;
}
declare module 'react-native-masked-text/lib/masks/custom.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/custom.mask'>;
}
declare module 'react-native-masked-text/lib/masks/datetime.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/datetime.mask'>;
}
declare module 'react-native-masked-text/lib/masks/index.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/index'>;
}
declare module 'react-native-masked-text/lib/masks/money.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/money.mask'>;
}
declare module 'react-native-masked-text/lib/masks/only-numbers.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/only-numbers.mask'>;
}
declare module 'react-native-masked-text/lib/masks/zip-code.mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/masks/zip-code.mask'>;
}
declare module 'react-native-masked-text/lib/text-input-mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/text-input-mask'>;
}
declare module 'react-native-masked-text/lib/text-mask.js' {
  declare module.exports: $Exports<'react-native-masked-text/lib/text-mask'>;
}
declare module 'react-native-masked-text/rnmt.js' {
  declare module.exports: $Exports<'react-native-masked-text/rnmt'>;
}
