// flow-typed signature: d8c1486c47dfe50ad58626a119b99735
// flow-typed version: <<STUB>>/react-phone-number-input_v^2.3.5/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-phone-number-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-phone-number-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-phone-number-input/basic-input-custom/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/basic-input-custom/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/basic-input/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/basic-input/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/build-bundle-styles' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-native-max' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-native-mobile' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-native' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-react-responsive-ui' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-smart-input' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/countries' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/CountrySelectNative' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/CountrySelectReactResponsiveUI' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/Flag' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/flags' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/formatPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/formatPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/input-control' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InputBasic' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InputBasicDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InputSmart' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InputSmartDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InternationalIcon' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/isValidPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/isValidPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputNative' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputNativeDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputNativeDefaults' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputReactResponsiveUI' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputReactResponsiveUIDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputReactResponsiveUIDefaults' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PropTypes' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/core/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/core/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/custom' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/fix-locales' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/flags/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/flags/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/international-icon/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/international-icon/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/libphonenumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/max/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/max/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/min/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/min/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/mobile/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/mobile/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/countries' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/CountrySelectNative' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/CountrySelectReactResponsiveUI' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/Flag' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/flags' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/formatPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/formatPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/input-control' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InputBasic' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InputBasicDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InputSmart' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InputSmartDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InternationalIcon' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/isValidPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/isValidPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputNative' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputNativeDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputNativeDefaults' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputReactResponsiveUI' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaults' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PropTypes' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/native-custom/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/native-custom/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/native' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-responsive-ui-custom/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-responsive-ui-custom/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-responsive-ui/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-responsive-ui/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-styleguidist' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/runnable/generate-country-flags' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/smart-input-custom/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/smart-input-custom/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/smart-input/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/smart-input/index' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-phone-number-input/basic-input-custom/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/basic-input-custom/index.commonjs'>;
}
declare module 'react-phone-number-input/basic-input-custom/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/basic-input-custom/index'>;
}
declare module 'react-phone-number-input/basic-input/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/basic-input/index.commonjs'>;
}
declare module 'react-phone-number-input/basic-input/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/basic-input/index'>;
}
declare module 'react-phone-number-input/build-bundle-styles.js' {
  declare module.exports: $Exports<'react-phone-number-input/build-bundle-styles'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-native-max.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-native-max'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-native-mobile.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-native-mobile'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-native.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-native'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-react-responsive-ui.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-react-responsive-ui'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-smart-input.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-smart-input'>;
}
declare module 'react-phone-number-input/commonjs/countries.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/countries'>;
}
declare module 'react-phone-number-input/commonjs/CountrySelectNative.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/CountrySelectNative'>;
}
declare module 'react-phone-number-input/commonjs/CountrySelectReactResponsiveUI.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/CountrySelectReactResponsiveUI'>;
}
declare module 'react-phone-number-input/commonjs/Flag.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/Flag'>;
}
declare module 'react-phone-number-input/commonjs/flags.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/flags'>;
}
declare module 'react-phone-number-input/commonjs/formatPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/formatPhoneNumber'>;
}
declare module 'react-phone-number-input/commonjs/formatPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/formatPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/input-control.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/input-control'>;
}
declare module 'react-phone-number-input/commonjs/InputBasic.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InputBasic'>;
}
declare module 'react-phone-number-input/commonjs/InputBasicDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InputBasicDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/InputSmart.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InputSmart'>;
}
declare module 'react-phone-number-input/commonjs/InputSmartDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InputSmartDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/InternationalIcon.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InternationalIcon'>;
}
declare module 'react-phone-number-input/commonjs/isValidPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/isValidPhoneNumber'>;
}
declare module 'react-phone-number-input/commonjs/isValidPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/isValidPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInput'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputNative.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputNative'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputNativeDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputNativeDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputNativeDefaults.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputNativeDefaults'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputReactResponsiveUI.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputReactResponsiveUI'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputReactResponsiveUIDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputReactResponsiveUIDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputReactResponsiveUIDefaults.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputReactResponsiveUIDefaults'>;
}
declare module 'react-phone-number-input/commonjs/PropTypes.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PropTypes'>;
}
declare module 'react-phone-number-input/core/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/core/index.commonjs'>;
}
declare module 'react-phone-number-input/core/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/core/index'>;
}
declare module 'react-phone-number-input/custom.js' {
  declare module.exports: $Exports<'react-phone-number-input/custom'>;
}
declare module 'react-phone-number-input/fix-locales.js' {
  declare module.exports: $Exports<'react-phone-number-input/fix-locales'>;
}
declare module 'react-phone-number-input/flags/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/flags/index.commonjs'>;
}
declare module 'react-phone-number-input/flags/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/flags/index'>;
}
declare module 'react-phone-number-input/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/index.commonjs'>;
}
declare module 'react-phone-number-input/index' {
  declare module.exports: $Exports<'react-phone-number-input'>;
}
declare module 'react-phone-number-input/index.js' {
  declare module.exports: $Exports<'react-phone-number-input'>;
}
declare module 'react-phone-number-input/international-icon/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/international-icon/index.commonjs'>;
}
declare module 'react-phone-number-input/international-icon/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/international-icon/index'>;
}
declare module 'react-phone-number-input/libphonenumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/libphonenumber'>;
}
declare module 'react-phone-number-input/max/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/max/index.commonjs'>;
}
declare module 'react-phone-number-input/max/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/max/index'>;
}
declare module 'react-phone-number-input/min/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/min/index.commonjs'>;
}
declare module 'react-phone-number-input/min/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/min/index'>;
}
declare module 'react-phone-number-input/mobile/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/mobile/index.commonjs'>;
}
declare module 'react-phone-number-input/mobile/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/mobile/index'>;
}
declare module 'react-phone-number-input/modules/countries.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/countries'>;
}
declare module 'react-phone-number-input/modules/CountrySelectNative.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/CountrySelectNative'>;
}
declare module 'react-phone-number-input/modules/CountrySelectReactResponsiveUI.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/CountrySelectReactResponsiveUI'>;
}
declare module 'react-phone-number-input/modules/Flag.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/Flag'>;
}
declare module 'react-phone-number-input/modules/flags.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/flags'>;
}
declare module 'react-phone-number-input/modules/formatPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/formatPhoneNumber'>;
}
declare module 'react-phone-number-input/modules/formatPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/formatPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/input-control.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/input-control'>;
}
declare module 'react-phone-number-input/modules/InputBasic.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InputBasic'>;
}
declare module 'react-phone-number-input/modules/InputBasicDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InputBasicDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/InputSmart.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InputSmart'>;
}
declare module 'react-phone-number-input/modules/InputSmartDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InputSmartDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/InternationalIcon.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InternationalIcon'>;
}
declare module 'react-phone-number-input/modules/isValidPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/isValidPhoneNumber'>;
}
declare module 'react-phone-number-input/modules/isValidPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/isValidPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/PhoneInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInput'>;
}
declare module 'react-phone-number-input/modules/PhoneInputNative.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputNative'>;
}
declare module 'react-phone-number-input/modules/PhoneInputNativeDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputNativeDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/PhoneInputNativeDefaults.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputNativeDefaults'>;
}
declare module 'react-phone-number-input/modules/PhoneInputReactResponsiveUI.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputReactResponsiveUI'>;
}
declare module 'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaults.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputReactResponsiveUIDefaults'>;
}
declare module 'react-phone-number-input/modules/PropTypes.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PropTypes'>;
}
declare module 'react-phone-number-input/native-custom/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/native-custom/index.commonjs'>;
}
declare module 'react-phone-number-input/native-custom/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/native-custom/index'>;
}
declare module 'react-phone-number-input/native.js' {
  declare module.exports: $Exports<'react-phone-number-input/native'>;
}
declare module 'react-phone-number-input/react-responsive-ui-custom/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-responsive-ui-custom/index.commonjs'>;
}
declare module 'react-phone-number-input/react-responsive-ui-custom/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-responsive-ui-custom/index'>;
}
declare module 'react-phone-number-input/react-responsive-ui/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-responsive-ui/index.commonjs'>;
}
declare module 'react-phone-number-input/react-responsive-ui/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-responsive-ui/index'>;
}
declare module 'react-phone-number-input/react-styleguidist.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-styleguidist'>;
}
declare module 'react-phone-number-input/runnable/generate-country-flags.js' {
  declare module.exports: $Exports<'react-phone-number-input/runnable/generate-country-flags'>;
}
declare module 'react-phone-number-input/smart-input-custom/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/smart-input-custom/index.commonjs'>;
}
declare module 'react-phone-number-input/smart-input-custom/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/smart-input-custom/index'>;
}
declare module 'react-phone-number-input/smart-input/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/smart-input/index.commonjs'>;
}
declare module 'react-phone-number-input/smart-input/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/smart-input/index'>;
}
declare module 'react-phone-number-input/webpack.config.js' {
  declare module.exports: $Exports<'react-phone-number-input/webpack.config'>;
}
