// flow-typed signature: 18818ec506b239d20f84fe64693e1258
// flow-typed version: <<STUB>>/react-app-polyfill_v^0.1.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-polyfill/ie11' {
  declare module.exports: any;
}

declare module 'react-app-polyfill/ie9' {
  declare module.exports: any;
}

declare module 'react-app-polyfill/jsdom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-polyfill/ie11.js' {
  declare module.exports: $Exports<'react-app-polyfill/ie11'>;
}
declare module 'react-app-polyfill/ie9.js' {
  declare module.exports: $Exports<'react-app-polyfill/ie9'>;
}
declare module 'react-app-polyfill/jsdom.js' {
  declare module.exports: $Exports<'react-app-polyfill/jsdom'>;
}
