// flow-typed signature: 275083d81813860e44ac75992d1e6265
// flow-typed version: <<STUB>>/react-native-elements_v^0.19.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-elements/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-native-elements/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/main' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/config/colors' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/config/fonts' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/config/socialColors' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/drawer/home' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/drawer/playground' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/drawer/pricing' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/drawer/ratings' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/tabs/buttons' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/tabs/fonts' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/tabs/forms' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/tabs/lists' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/buttons_detail' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/buttons_home' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/fonts_detail' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/fonts_home' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/forms_details' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/forms_home' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/lists_detail' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/lists_home' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/playground' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/pricing' {
  declare module.exports: any;
}

declare module 'react-native-elements/example/src/views/ratings' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/avatar/__tests__/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/avatar/Avatar' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/badge/__tests__/badge' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/badge/badge' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/__tests__/Button' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/__tests__/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/Button' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/buttons/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/__tests__/Card' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/card/Card' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/checkbox/__tests__/CheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/checkbox/CheckBox' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/BackgroundImage' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/colors' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/fonts' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/config/ViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/divider/__tests__/Divider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/divider/Divider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/form/__tests__/FormInput' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/form/__tests__/FormLabel' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/form/__tests__/FormValidationMessage' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/form/FormInput' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/form/FormLabel' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/form/FormValidationMessage' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/__tests__/DummyNavButton' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/__tests__/Header' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/__tests__/NavButton' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/__tests__/Title' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/DummyNavButton' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/Header' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/NavButton' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/header/Title' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/getIconType' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/helpers/normalizeText' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/icons/__tests__/Icon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/icons/Icon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/index' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/input/__tests__/Search' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/input/Search' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/__tests__/List' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/__tests__/ListItem' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/List' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/list/ListItem' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/pricing/__tests__/PricingCard' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/pricing/PricingCard' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/rating/__tests__/Rating' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/rating/Rating' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/slider/__tests__/Slider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/slider/Slider' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/social/__tests__/SocialIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/social/SocialIcon' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/text/__tests__/Text' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/text/Text' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/__tests__/FeaturedTile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/__tests__/Tile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/FeaturedTile' {
  declare module.exports: any;
}

declare module 'react-native-elements/src/tile/Tile' {
  declare module.exports: any;
}

declare module 'react-native-elements/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-elements/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-native-elements/coverage/lcov-report/prettify'>;
}
declare module 'react-native-elements/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-native-elements/coverage/lcov-report/sorter'>;
}
declare module 'react-native-elements/example/main.js' {
  declare module.exports: $Exports<'react-native-elements/example/main'>;
}
declare module 'react-native-elements/example/src/config/colors.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/config/colors'>;
}
declare module 'react-native-elements/example/src/config/fonts.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/config/fonts'>;
}
declare module 'react-native-elements/example/src/config/socialColors.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/config/socialColors'>;
}
declare module 'react-native-elements/example/src/drawer/home.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/drawer/home'>;
}
declare module 'react-native-elements/example/src/drawer/playground.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/drawer/playground'>;
}
declare module 'react-native-elements/example/src/drawer/pricing.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/drawer/pricing'>;
}
declare module 'react-native-elements/example/src/drawer/ratings.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/drawer/ratings'>;
}
declare module 'react-native-elements/example/src/tabs/buttons.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/tabs/buttons'>;
}
declare module 'react-native-elements/example/src/tabs/fonts.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/tabs/fonts'>;
}
declare module 'react-native-elements/example/src/tabs/forms.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/tabs/forms'>;
}
declare module 'react-native-elements/example/src/tabs/lists.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/tabs/lists'>;
}
declare module 'react-native-elements/example/src/views/buttons_detail.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/buttons_detail'>;
}
declare module 'react-native-elements/example/src/views/buttons_home.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/buttons_home'>;
}
declare module 'react-native-elements/example/src/views/fonts_detail.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/fonts_detail'>;
}
declare module 'react-native-elements/example/src/views/fonts_home.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/fonts_home'>;
}
declare module 'react-native-elements/example/src/views/forms_details.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/forms_details'>;
}
declare module 'react-native-elements/example/src/views/forms_home.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/forms_home'>;
}
declare module 'react-native-elements/example/src/views/lists_detail.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/lists_detail'>;
}
declare module 'react-native-elements/example/src/views/lists_home.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/lists_home'>;
}
declare module 'react-native-elements/example/src/views/playground.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/playground'>;
}
declare module 'react-native-elements/example/src/views/pricing.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/pricing'>;
}
declare module 'react-native-elements/example/src/views/ratings.js' {
  declare module.exports: $Exports<'react-native-elements/example/src/views/ratings'>;
}
declare module 'react-native-elements/src/avatar/__tests__/Avatar.js' {
  declare module.exports: $Exports<'react-native-elements/src/avatar/__tests__/Avatar'>;
}
declare module 'react-native-elements/src/avatar/Avatar.js' {
  declare module.exports: $Exports<'react-native-elements/src/avatar/Avatar'>;
}
declare module 'react-native-elements/src/badge/__tests__/badge.js' {
  declare module.exports: $Exports<'react-native-elements/src/badge/__tests__/badge'>;
}
declare module 'react-native-elements/src/badge/badge.js' {
  declare module.exports: $Exports<'react-native-elements/src/badge/badge'>;
}
declare module 'react-native-elements/src/buttons/__tests__/Button.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/__tests__/Button'>;
}
declare module 'react-native-elements/src/buttons/__tests__/ButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/__tests__/ButtonGroup'>;
}
declare module 'react-native-elements/src/buttons/Button.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/Button'>;
}
declare module 'react-native-elements/src/buttons/ButtonGroup.js' {
  declare module.exports: $Exports<'react-native-elements/src/buttons/ButtonGroup'>;
}
declare module 'react-native-elements/src/card/__tests__/Card.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/__tests__/Card'>;
}
declare module 'react-native-elements/src/card/Card.js' {
  declare module.exports: $Exports<'react-native-elements/src/card/Card'>;
}
declare module 'react-native-elements/src/checkbox/__tests__/CheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/src/checkbox/__tests__/CheckBox'>;
}
declare module 'react-native-elements/src/checkbox/CheckBox.js' {
  declare module.exports: $Exports<'react-native-elements/src/checkbox/CheckBox'>;
}
declare module 'react-native-elements/src/config/BackgroundImage.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/BackgroundImage'>;
}
declare module 'react-native-elements/src/config/colors.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/colors'>;
}
declare module 'react-native-elements/src/config/fonts.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/fonts'>;
}
declare module 'react-native-elements/src/config/ViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-elements/src/config/ViewPropTypes'>;
}
declare module 'react-native-elements/src/divider/__tests__/Divider.js' {
  declare module.exports: $Exports<'react-native-elements/src/divider/__tests__/Divider'>;
}
declare module 'react-native-elements/src/divider/Divider.js' {
  declare module.exports: $Exports<'react-native-elements/src/divider/Divider'>;
}
declare module 'react-native-elements/src/form/__tests__/FormInput.js' {
  declare module.exports: $Exports<'react-native-elements/src/form/__tests__/FormInput'>;
}
declare module 'react-native-elements/src/form/__tests__/FormLabel.js' {
  declare module.exports: $Exports<'react-native-elements/src/form/__tests__/FormLabel'>;
}
declare module 'react-native-elements/src/form/__tests__/FormValidationMessage.js' {
  declare module.exports: $Exports<'react-native-elements/src/form/__tests__/FormValidationMessage'>;
}
declare module 'react-native-elements/src/form/FormInput.js' {
  declare module.exports: $Exports<'react-native-elements/src/form/FormInput'>;
}
declare module 'react-native-elements/src/form/FormLabel.js' {
  declare module.exports: $Exports<'react-native-elements/src/form/FormLabel'>;
}
declare module 'react-native-elements/src/form/FormValidationMessage.js' {
  declare module.exports: $Exports<'react-native-elements/src/form/FormValidationMessage'>;
}
declare module 'react-native-elements/src/header/__tests__/DummyNavButton.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/__tests__/DummyNavButton'>;
}
declare module 'react-native-elements/src/header/__tests__/Header.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/__tests__/Header'>;
}
declare module 'react-native-elements/src/header/__tests__/NavButton.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/__tests__/NavButton'>;
}
declare module 'react-native-elements/src/header/__tests__/Title.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/__tests__/Title'>;
}
declare module 'react-native-elements/src/header/DummyNavButton.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/DummyNavButton'>;
}
declare module 'react-native-elements/src/header/Header.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/Header'>;
}
declare module 'react-native-elements/src/header/NavButton.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/NavButton'>;
}
declare module 'react-native-elements/src/header/Title.js' {
  declare module.exports: $Exports<'react-native-elements/src/header/Title'>;
}
declare module 'react-native-elements/src/helpers/getIconType.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/getIconType'>;
}
declare module 'react-native-elements/src/helpers/normalizeText.js' {
  declare module.exports: $Exports<'react-native-elements/src/helpers/normalizeText'>;
}
declare module 'react-native-elements/src/icons/__tests__/Icon.js' {
  declare module.exports: $Exports<'react-native-elements/src/icons/__tests__/Icon'>;
}
declare module 'react-native-elements/src/icons/Icon.js' {
  declare module.exports: $Exports<'react-native-elements/src/icons/Icon'>;
}
declare module 'react-native-elements/src/index.js' {
  declare module.exports: $Exports<'react-native-elements/src/index'>;
}
declare module 'react-native-elements/src/input/__tests__/Search.js' {
  declare module.exports: $Exports<'react-native-elements/src/input/__tests__/Search'>;
}
declare module 'react-native-elements/src/input/Search.js' {
  declare module.exports: $Exports<'react-native-elements/src/input/Search'>;
}
declare module 'react-native-elements/src/list/__tests__/List.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/__tests__/List'>;
}
declare module 'react-native-elements/src/list/__tests__/ListItem.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/__tests__/ListItem'>;
}
declare module 'react-native-elements/src/list/List.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/List'>;
}
declare module 'react-native-elements/src/list/ListItem.js' {
  declare module.exports: $Exports<'react-native-elements/src/list/ListItem'>;
}
declare module 'react-native-elements/src/pricing/__tests__/PricingCard.js' {
  declare module.exports: $Exports<'react-native-elements/src/pricing/__tests__/PricingCard'>;
}
declare module 'react-native-elements/src/pricing/PricingCard.js' {
  declare module.exports: $Exports<'react-native-elements/src/pricing/PricingCard'>;
}
declare module 'react-native-elements/src/rating/__tests__/Rating.js' {
  declare module.exports: $Exports<'react-native-elements/src/rating/__tests__/Rating'>;
}
declare module 'react-native-elements/src/rating/Rating.js' {
  declare module.exports: $Exports<'react-native-elements/src/rating/Rating'>;
}
declare module 'react-native-elements/src/slider/__tests__/Slider.js' {
  declare module.exports: $Exports<'react-native-elements/src/slider/__tests__/Slider'>;
}
declare module 'react-native-elements/src/slider/Slider.js' {
  declare module.exports: $Exports<'react-native-elements/src/slider/Slider'>;
}
declare module 'react-native-elements/src/social/__tests__/SocialIcon.js' {
  declare module.exports: $Exports<'react-native-elements/src/social/__tests__/SocialIcon'>;
}
declare module 'react-native-elements/src/social/SocialIcon.js' {
  declare module.exports: $Exports<'react-native-elements/src/social/SocialIcon'>;
}
declare module 'react-native-elements/src/text/__tests__/Text.js' {
  declare module.exports: $Exports<'react-native-elements/src/text/__tests__/Text'>;
}
declare module 'react-native-elements/src/text/Text.js' {
  declare module.exports: $Exports<'react-native-elements/src/text/Text'>;
}
declare module 'react-native-elements/src/tile/__tests__/FeaturedTile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/__tests__/FeaturedTile'>;
}
declare module 'react-native-elements/src/tile/__tests__/Tile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/__tests__/Tile'>;
}
declare module 'react-native-elements/src/tile/FeaturedTile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/FeaturedTile'>;
}
declare module 'react-native-elements/src/tile/Tile.js' {
  declare module.exports: $Exports<'react-native-elements/src/tile/Tile'>;
}
declare module 'react-native-elements/webpack.config.js' {
  declare module.exports: $Exports<'react-native-elements/webpack.config'>;
}
