// flow-typed signature: 9920ff0af8e42c42ce9faa4b3d12ca4c
// flow-typed version: <<STUB>>/recaptcha-v3-react_v^3.0.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'recaptcha-v3-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'recaptcha-v3-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'recaptcha-v3-react/dist/index' {
  declare module.exports: any;
}

declare module 'recaptcha-v3-react/lib/index' {
  declare module.exports: any;
}

declare module 'recaptcha-v3-react/lib/loadReCaptcha' {
  declare module.exports: any;
}

declare module 'recaptcha-v3-react/lib/ReCaptcha' {
  declare module.exports: any;
}

declare module 'recaptcha-v3-react/src/index' {
  declare module.exports: any;
}

declare module 'recaptcha-v3-react/src/loadReCaptcha' {
  declare module.exports: any;
}

declare module 'recaptcha-v3-react/src/ReCaptcha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'recaptcha-v3-react/dist/index.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/dist/index'>;
}
declare module 'recaptcha-v3-react/lib/index.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/lib/index'>;
}
declare module 'recaptcha-v3-react/lib/loadReCaptcha.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/lib/loadReCaptcha'>;
}
declare module 'recaptcha-v3-react/lib/ReCaptcha.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/lib/ReCaptcha'>;
}
declare module 'recaptcha-v3-react/src/index.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/src/index'>;
}
declare module 'recaptcha-v3-react/src/loadReCaptcha.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/src/loadReCaptcha'>;
}
declare module 'recaptcha-v3-react/src/ReCaptcha.js' {
  declare module.exports: $Exports<'recaptcha-v3-react/src/ReCaptcha'>;
}
