// flow-typed signature: e94419cfad7efe6b075e204b3e509ff3
// flow-typed version: <<STUB>>/undux_v5.0.0-beta.19/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'undux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'undux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'undux/dist.esnext/index' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/plugins/withLogger' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/plugins/withReduxDevtools' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/react/connect' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/react/connectAs' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/react/createConnectedStore' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/react/createConnectedStoreAs' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/react/index' {
  declare module.exports: any;
}

declare module 'undux/dist.esnext/utils' {
  declare module.exports: any;
}

declare module 'undux/dist/src/index' {
  declare module.exports: any;
}

declare module 'undux/dist/src/Observable' {
  declare module.exports: any;
}

declare module 'undux/dist/src/plugins/withLogger' {
  declare module.exports: any;
}

declare module 'undux/dist/src/plugins/withReduxDevtools' {
  declare module.exports: any;
}

declare module 'undux/dist/src/react/connect' {
  declare module.exports: any;
}

declare module 'undux/dist/src/react/connectAs' {
  declare module.exports: any;
}

declare module 'undux/dist/src/react/createConnectedStore' {
  declare module.exports: any;
}

declare module 'undux/dist/src/react/createConnectedStoreAs' {
  declare module.exports: any;
}

declare module 'undux/dist/src/react/index' {
  declare module.exports: any;
}

declare module 'undux/dist/src/utils' {
  declare module.exports: any;
}

declare module 'undux/flow-typed/npm/rxjs_v5.0.x' {
  declare module.exports: any;
}

// Filename aliases
declare module 'undux/dist.esnext/index.js' {
  declare module.exports: $Exports<'undux/dist.esnext/index'>;
}
declare module 'undux/dist.esnext/plugins/withLogger.js' {
  declare module.exports: $Exports<'undux/dist.esnext/plugins/withLogger'>;
}
declare module 'undux/dist.esnext/plugins/withReduxDevtools.js' {
  declare module.exports: $Exports<'undux/dist.esnext/plugins/withReduxDevtools'>;
}
declare module 'undux/dist.esnext/react/connect.js' {
  declare module.exports: $Exports<'undux/dist.esnext/react/connect'>;
}
declare module 'undux/dist.esnext/react/connectAs.js' {
  declare module.exports: $Exports<'undux/dist.esnext/react/connectAs'>;
}
declare module 'undux/dist.esnext/react/createConnectedStore.js' {
  declare module.exports: $Exports<'undux/dist.esnext/react/createConnectedStore'>;
}
declare module 'undux/dist.esnext/react/createConnectedStoreAs.js' {
  declare module.exports: $Exports<'undux/dist.esnext/react/createConnectedStoreAs'>;
}
declare module 'undux/dist.esnext/react/index.js' {
  declare module.exports: $Exports<'undux/dist.esnext/react/index'>;
}
declare module 'undux/dist.esnext/utils.js' {
  declare module.exports: $Exports<'undux/dist.esnext/utils'>;
}
declare module 'undux/dist/src/index.js' {
  declare module.exports: $Exports<'undux/dist/src/index'>;
}
declare module 'undux/dist/src/Observable.js' {
  declare module.exports: $Exports<'undux/dist/src/Observable'>;
}
declare module 'undux/dist/src/plugins/withLogger.js' {
  declare module.exports: $Exports<'undux/dist/src/plugins/withLogger'>;
}
declare module 'undux/dist/src/plugins/withReduxDevtools.js' {
  declare module.exports: $Exports<'undux/dist/src/plugins/withReduxDevtools'>;
}
declare module 'undux/dist/src/react/connect.js' {
  declare module.exports: $Exports<'undux/dist/src/react/connect'>;
}
declare module 'undux/dist/src/react/connectAs.js' {
  declare module.exports: $Exports<'undux/dist/src/react/connectAs'>;
}
declare module 'undux/dist/src/react/createConnectedStore.js' {
  declare module.exports: $Exports<'undux/dist/src/react/createConnectedStore'>;
}
declare module 'undux/dist/src/react/createConnectedStoreAs.js' {
  declare module.exports: $Exports<'undux/dist/src/react/createConnectedStoreAs'>;
}
declare module 'undux/dist/src/react/index.js' {
  declare module.exports: $Exports<'undux/dist/src/react/index'>;
}
declare module 'undux/dist/src/utils.js' {
  declare module.exports: $Exports<'undux/dist/src/utils'>;
}
declare module 'undux/flow-typed/npm/rxjs_v5.0.x.js' {
  declare module.exports: $Exports<'undux/flow-typed/npm/rxjs_v5.0.x'>;
}
