// flow-typed signature: ae9fade8ff105146c6692c0e858b71d5
// flow-typed version: <<STUB>>/web3-providers-http_v1.0.0-beta.37/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-providers-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare class HttpProvider {
  _prepareRequest: () => any;
  send: (payload: any, callback: Function) => null;
  disconnect: () => null;
}

declare module 'web3-providers-http' {
  declare module.exports: {
    HttpProvider: typeof HttpProvider
  };
}
