// flow-typed signature: 35fc0d23cc9552e061af413842c551ab
// flow-typed version: <<STUB>>/web3_v^1.0.0-beta.55/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3/angular-patch' {
  declare module.exports: any;
}

declare module 'web3/dist/web3.cjs' {
  declare module.exports: any;
}

declare module 'web3/dist/web3.esm' {
  declare module.exports: any;
}

declare module 'web3/dist/web3.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3/angular-patch.js' {
  declare module.exports: $Exports<'web3/angular-patch'>;
}
declare module 'web3/dist/web3.cjs.js' {
  declare module.exports: $Exports<'web3/dist/web3.cjs'>;
}
declare module 'web3/dist/web3.esm.js' {
  declare module.exports: $Exports<'web3/dist/web3.esm'>;
}
declare module 'web3/dist/web3.umd.js' {
  declare module.exports: $Exports<'web3/dist/web3.umd'>;
}
