// flow-typed signature: b920868c5c0ac01cd9d1250facc71c60
// flow-typed version: <<STUB>>/web3-providers_v^1.0.0-beta.55/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-providers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-providers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-providers/dist/web3-providers.cjs' {
  declare module.exports: any;
}

declare module 'web3-providers/dist/web3-providers.esm' {
  declare module.exports: any;
}

declare module 'web3-providers/dist/web3-providers.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-providers/dist/web3-providers.cjs.js' {
  declare module.exports: $Exports<'web3-providers/dist/web3-providers.cjs'>;
}
declare module 'web3-providers/dist/web3-providers.esm.js' {
  declare module.exports: $Exports<'web3-providers/dist/web3-providers.esm'>;
}
declare module 'web3-providers/dist/web3-providers.umd.js' {
  declare module.exports: $Exports<'web3-providers/dist/web3-providers.umd'>;
}
