// flow-typed signature: 95b094de1a30539d022b6779451db846
// flow-typed version: <<STUB>>/web3_v1.0.0-beta.37/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3/src/index.js' {
  declare module.exports: $Exports<'web3/src/index'>;
}
