// flow-typed signature: 01660e082c59c9a3f7d5c8864e18ad3f
// flow-typed version: <<STUB>>/@gooddollar/goodcontracts_v^0.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@gooddollar/goodcontracts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@gooddollar/goodcontracts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@gooddollar/goodcontracts/contracts/releaser' {
  declare module.exports: any;
}

declare module '@gooddollar/goodcontracts/test/GoodCoinMarket' {
  declare module.exports: any;
}

declare module '@gooddollar/goodcontracts/test/GoodDollar' {
  declare module.exports: any;
}

// Filename aliases
declare module '@gooddollar/goodcontracts/contracts/releaser.js' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/contracts/releaser'>;
}
declare module '@gooddollar/goodcontracts/test/GoodCoinMarket.js' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/test/GoodCoinMarket'>;
}
declare module '@gooddollar/goodcontracts/test/GoodDollar.js' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/test/GoodDollar'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/Identity.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/Identity.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/RedemptionFunctional.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/RedemptionFunctional.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/GoodDollar.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/GoodDollar.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/GoodDollarReserve.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/GoodDollarReserve.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/OneTimePaymentLinks.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/OneTimePaymentLinks.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/Identity.min.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/Identity.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/RedemptionFunctional.min.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/RedemptionFunctional.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/GoodDollar.min.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/GoodDollar.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/GoodDollarReserve.min.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/GoodDollarReserve.json'>;
}
declare module '@gooddollar/goodcontracts/build/contracts/OneTimePaymentLinks.min.json' {
  declare module.exports: $Exports<'@gooddollar/goodcontracts/build/contracts/OneTimePaymentLinks.json'>;
}
