// flow-typed signature: abba118957f124f249cdf39af7c921e9
// flow-typed version: <<STUB>>/@gooddollar/gun-appendonly_v^1.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@gooddollar/gun-appendonly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@gooddollar/gun-appendonly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@gooddollar/gun-appendonly/dist/gun-appendOnly' {
  declare module.exports: any;
}

declare module '@gooddollar/gun-appendonly/src/gun-appendOnly' {
  declare module.exports: any;
}

// Filename aliases
declare module '@gooddollar/gun-appendonly/dist/gun-appendOnly.js' {
  declare module.exports: $Exports<'@gooddollar/gun-appendonly/dist/gun-appendOnly'>;
}
declare module '@gooddollar/gun-appendonly/src/gun-appendOnly.js' {
  declare module.exports: $Exports<'@gooddollar/gun-appendonly/src/gun-appendOnly'>;
}
