// flow-typed signature: 476d8ba0752c6ad98952b3d4715785b2
// flow-typed version: <<STUB>>/@trust/webcrypto_v^0.9.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@trust/webcrypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@trust/webcrypto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@trust/webcrypto/src/algorithms/AES-CBC' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/AES-CTR' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/AES-GCM' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/AES-KW' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/Algorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/ECDSA' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/EDDSA' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/HMAC' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/index' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/RegisteredAlgorithms' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/RSA-OAEP' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/RSA-PSS' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/RSASSA-PKCS1-v1_5' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/SHA' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/algorithms/SupportedAlgorithms' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/Crypto' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AES-KW' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesCbcParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesCfbParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesCmacParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesCtrParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesDerivedKeyParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesGcmParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/AesKeyGenParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/Algorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/ConcatParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/DhImportKeyParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/DhKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/DhKeyDeriveParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/DhKeyGenParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/EcdhKeyDeriveParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/EcdsaParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/EcKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/EcKeyGenParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/EcKeyImportParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/HkdfCtrParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/HmacImportParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/HmacKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/HmacKeyGenParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/KeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/Pbkdf2Params' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaHashedImportParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaHashedKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaHashedKeyGenParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaKeyGenParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaOaepParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/RsaPssParams' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/dictionaries/ShaKeyAlgorithm' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/CurrentlyNotSupportedError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/DataError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/index' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/InvalidAccessError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/KeyFormatNotSupportedError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/NotSupportedError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/OperationError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/QuotaExceededError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/errors/TypeMismatchError' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/index' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/keys/CryptoKey' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/keys/CryptoKeyPair' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/keys/JsonWebKey' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/keys/recognizedKeyUsages' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/src/SubtleCrypto' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/AES-CBCSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/AES-CTRSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/AES-GCMSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/AES-KWSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/ECDSASpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/EDDSASpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/HMACSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/RegisteredAlgorithmsSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/RSA-OAEPspec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/RSA-PSSSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/RSASSA-PKCS1-v1_5_Spec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/SHASpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/algorithms/SupportedAlgorithmsSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/CryptoSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/dictionaries/AlgorithmSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/dictionaries/HmacKeyAlgorithmSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/dictionaries/KeyAlgorithmSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/dictionaries/RsaHashedKeyAlgorithmSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/dictionaries/ShaKeyAlgorithmSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/EcdsaKeyPairsForTesting' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/keys/CryptoKeyPairSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/keys/CryptoKeySpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/keys/JsonWebKeySpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/keys/recognizedKeyUsagesSpec' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/RsaKeyPairForPSSTesting' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/RsaKeyPairForTesting' {
  declare module.exports: any;
}

declare module '@trust/webcrypto/test/SubtleCryptoSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@trust/webcrypto/src/algorithms/AES-CBC.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/AES-CBC'>;
}
declare module '@trust/webcrypto/src/algorithms/AES-CTR.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/AES-CTR'>;
}
declare module '@trust/webcrypto/src/algorithms/AES-GCM.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/AES-GCM'>;
}
declare module '@trust/webcrypto/src/algorithms/AES-KW.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/AES-KW'>;
}
declare module '@trust/webcrypto/src/algorithms/Algorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/Algorithm'>;
}
declare module '@trust/webcrypto/src/algorithms/ECDSA.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/ECDSA'>;
}
declare module '@trust/webcrypto/src/algorithms/EDDSA.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/EDDSA'>;
}
declare module '@trust/webcrypto/src/algorithms/HMAC.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/HMAC'>;
}
declare module '@trust/webcrypto/src/algorithms/index.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/index'>;
}
declare module '@trust/webcrypto/src/algorithms/RegisteredAlgorithms.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/RegisteredAlgorithms'>;
}
declare module '@trust/webcrypto/src/algorithms/RSA-OAEP.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/RSA-OAEP'>;
}
declare module '@trust/webcrypto/src/algorithms/RSA-PSS.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/RSA-PSS'>;
}
declare module '@trust/webcrypto/src/algorithms/RSASSA-PKCS1-v1_5.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/RSASSA-PKCS1-v1_5'>;
}
declare module '@trust/webcrypto/src/algorithms/SHA.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/SHA'>;
}
declare module '@trust/webcrypto/src/algorithms/SupportedAlgorithms.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/algorithms/SupportedAlgorithms'>;
}
declare module '@trust/webcrypto/src/Crypto.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/Crypto'>;
}
declare module '@trust/webcrypto/src/dictionaries/AES-KW.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AES-KW'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesCbcParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesCbcParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesCfbParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesCfbParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesCmacParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesCmacParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesCtrParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesCtrParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesDerivedKeyParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesDerivedKeyParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesGcmParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesGcmParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/AesKeyGenParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/AesKeyGenParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/Algorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/Algorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/ConcatParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/ConcatParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/DhImportKeyParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/DhImportKeyParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/DhKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/DhKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/DhKeyDeriveParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/DhKeyDeriveParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/DhKeyGenParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/DhKeyGenParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/EcdhKeyDeriveParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/EcdhKeyDeriveParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/EcdsaParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/EcdsaParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/EcKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/EcKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/EcKeyGenParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/EcKeyGenParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/EcKeyImportParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/EcKeyImportParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/HkdfCtrParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/HkdfCtrParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/HmacImportParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/HmacImportParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/HmacKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/HmacKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/HmacKeyGenParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/HmacKeyGenParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/KeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/KeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/Pbkdf2Params.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/Pbkdf2Params'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaHashedImportParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaHashedImportParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaHashedKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaHashedKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaHashedKeyGenParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaHashedKeyGenParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaKeyGenParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaKeyGenParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaOaepParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaOaepParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/RsaPssParams.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/RsaPssParams'>;
}
declare module '@trust/webcrypto/src/dictionaries/ShaKeyAlgorithm.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/dictionaries/ShaKeyAlgorithm'>;
}
declare module '@trust/webcrypto/src/errors/CurrentlyNotSupportedError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/CurrentlyNotSupportedError'>;
}
declare module '@trust/webcrypto/src/errors/DataError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/DataError'>;
}
declare module '@trust/webcrypto/src/errors/index.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/index'>;
}
declare module '@trust/webcrypto/src/errors/InvalidAccessError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/InvalidAccessError'>;
}
declare module '@trust/webcrypto/src/errors/KeyFormatNotSupportedError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/KeyFormatNotSupportedError'>;
}
declare module '@trust/webcrypto/src/errors/NotSupportedError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/NotSupportedError'>;
}
declare module '@trust/webcrypto/src/errors/OperationError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/OperationError'>;
}
declare module '@trust/webcrypto/src/errors/QuotaExceededError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/QuotaExceededError'>;
}
declare module '@trust/webcrypto/src/errors/TypeMismatchError.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/errors/TypeMismatchError'>;
}
declare module '@trust/webcrypto/src/index.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/index'>;
}
declare module '@trust/webcrypto/src/keys/CryptoKey.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/keys/CryptoKey'>;
}
declare module '@trust/webcrypto/src/keys/CryptoKeyPair.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/keys/CryptoKeyPair'>;
}
declare module '@trust/webcrypto/src/keys/JsonWebKey.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/keys/JsonWebKey'>;
}
declare module '@trust/webcrypto/src/keys/recognizedKeyUsages.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/keys/recognizedKeyUsages'>;
}
declare module '@trust/webcrypto/src/SubtleCrypto.js' {
  declare module.exports: $Exports<'@trust/webcrypto/src/SubtleCrypto'>;
}
declare module '@trust/webcrypto/test/algorithms/AES-CBCSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/AES-CBCSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/AES-CTRSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/AES-CTRSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/AES-GCMSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/AES-GCMSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/AES-KWSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/AES-KWSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/ECDSASpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/ECDSASpec'>;
}
declare module '@trust/webcrypto/test/algorithms/EDDSASpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/EDDSASpec'>;
}
declare module '@trust/webcrypto/test/algorithms/HMACSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/HMACSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/RegisteredAlgorithmsSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/RegisteredAlgorithmsSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/RSA-OAEPspec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/RSA-OAEPspec'>;
}
declare module '@trust/webcrypto/test/algorithms/RSA-PSSSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/RSA-PSSSpec'>;
}
declare module '@trust/webcrypto/test/algorithms/RSASSA-PKCS1-v1_5_Spec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/RSASSA-PKCS1-v1_5_Spec'>;
}
declare module '@trust/webcrypto/test/algorithms/SHASpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/SHASpec'>;
}
declare module '@trust/webcrypto/test/algorithms/SupportedAlgorithmsSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/algorithms/SupportedAlgorithmsSpec'>;
}
declare module '@trust/webcrypto/test/CryptoSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/CryptoSpec'>;
}
declare module '@trust/webcrypto/test/dictionaries/AlgorithmSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/dictionaries/AlgorithmSpec'>;
}
declare module '@trust/webcrypto/test/dictionaries/HmacKeyAlgorithmSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/dictionaries/HmacKeyAlgorithmSpec'>;
}
declare module '@trust/webcrypto/test/dictionaries/KeyAlgorithmSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/dictionaries/KeyAlgorithmSpec'>;
}
declare module '@trust/webcrypto/test/dictionaries/RsaHashedKeyAlgorithmSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/dictionaries/RsaHashedKeyAlgorithmSpec'>;
}
declare module '@trust/webcrypto/test/dictionaries/ShaKeyAlgorithmSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/dictionaries/ShaKeyAlgorithmSpec'>;
}
declare module '@trust/webcrypto/test/EcdsaKeyPairsForTesting.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/EcdsaKeyPairsForTesting'>;
}
declare module '@trust/webcrypto/test/keys/CryptoKeyPairSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/keys/CryptoKeyPairSpec'>;
}
declare module '@trust/webcrypto/test/keys/CryptoKeySpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/keys/CryptoKeySpec'>;
}
declare module '@trust/webcrypto/test/keys/JsonWebKeySpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/keys/JsonWebKeySpec'>;
}
declare module '@trust/webcrypto/test/keys/recognizedKeyUsagesSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/keys/recognizedKeyUsagesSpec'>;
}
declare module '@trust/webcrypto/test/RsaKeyPairForPSSTesting.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/RsaKeyPairForPSSTesting'>;
}
declare module '@trust/webcrypto/test/RsaKeyPairForTesting.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/RsaKeyPairForTesting'>;
}
declare module '@trust/webcrypto/test/SubtleCryptoSpec.js' {
  declare module.exports: $Exports<'@trust/webcrypto/test/SubtleCryptoSpec'>;
}
