// flow-typed signature: d48a67a7ab3f4747512bae63aab23ac7
// flow-typed version: <<STUB>>/@react-navigation/core_v^3.0.2/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/core/dist/getChildEventSubscriber' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/getChildNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/getChildrenNavigationCache' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/getChildRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/getNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/index' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/NavigationActions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/navigators/createNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/navigators/createSwitchNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/createConfigGetter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/getNavigationActionCreators' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/getScreenForRouteName' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/KeyGenerator' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/pathUtils' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/StackActions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/StackRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/SwitchRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/TabRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/validateRouteConfigMap' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/routers/validateScreenOptions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/StateUtils' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/utils/docsUrl' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/utils/getActiveChildNavigationOptions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/utils/getSceneIndicesForInterpolationInputRange' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/utils/invariant' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/utils/withDefaultValue' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/NavigationConsumer' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/NavigationContext' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/NavigationEvents' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/NavigationProvider' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/SceneView' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/SwitchView/SwitchView' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/withNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/core/dist/views/withNavigationFocus' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/__tests__/getChildEventSubscriber-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/__tests__/getNavigation-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/__tests__/NavigationActions-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/__tests__/NavigationStateUtils-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/getChildEventSubscriber' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/getChildNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/getChildrenNavigationCache' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/getNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/index' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/NavigationActions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/navigators/createNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/navigators/createSwitchNavigator' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/createConfigGetter-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/PathHandling-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/pathUtils-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/Routers-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/StackRouter-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/SwitchRouter-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/TabRouter-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/__tests__/validateRouteConfigMap-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/createConfigGetter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/getNavigationActionCreators' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/getScreenForRouteName' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/pathUtils' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/StackActions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/StackRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/SwitchRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/TabRouter' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/validateRouteConfigMap' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/routers/validateScreenOptions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/StateUtils' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/utils/docsUrl' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/utils/getActiveChildNavigationOptions' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/utils/getSceneIndicesForInterpolationInputRange' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/utils/invariant' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/utils/withDefaultValue' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/__tests__/NavigationEvents-test' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/NavigationConsumer' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/NavigationContext' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/NavigationEvents' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/NavigationProvider' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/SceneView' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/SwitchView/SwitchView' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/withNavigation' {
  declare module.exports: any;
}

declare module '@react-navigation/core/src/views/withNavigationFocus' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/core/dist/getChildEventSubscriber.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/getChildEventSubscriber'>;
}
declare module '@react-navigation/core/dist/getChildNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/getChildNavigation'>;
}
declare module '@react-navigation/core/dist/getChildrenNavigationCache.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/getChildrenNavigationCache'>;
}
declare module '@react-navigation/core/dist/getChildRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/getChildRouter'>;
}
declare module '@react-navigation/core/dist/getNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/getNavigation'>;
}
declare module '@react-navigation/core/dist/index.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/index'>;
}
declare module '@react-navigation/core/dist/NavigationActions.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/NavigationActions'>;
}
declare module '@react-navigation/core/dist/navigators/createNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/navigators/createNavigator'>;
}
declare module '@react-navigation/core/dist/navigators/createSwitchNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/navigators/createSwitchNavigator'>;
}
declare module '@react-navigation/core/dist/routers/createConfigGetter.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/createConfigGetter'>;
}
declare module '@react-navigation/core/dist/routers/getNavigationActionCreators.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/getNavigationActionCreators'>;
}
declare module '@react-navigation/core/dist/routers/getScreenForRouteName.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/getScreenForRouteName'>;
}
declare module '@react-navigation/core/dist/routers/KeyGenerator.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/KeyGenerator'>;
}
declare module '@react-navigation/core/dist/routers/pathUtils.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/pathUtils'>;
}
declare module '@react-navigation/core/dist/routers/StackActions.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/StackActions'>;
}
declare module '@react-navigation/core/dist/routers/StackRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/StackRouter'>;
}
declare module '@react-navigation/core/dist/routers/SwitchRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/SwitchRouter'>;
}
declare module '@react-navigation/core/dist/routers/TabRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/TabRouter'>;
}
declare module '@react-navigation/core/dist/routers/validateRouteConfigMap.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/validateRouteConfigMap'>;
}
declare module '@react-navigation/core/dist/routers/validateScreenOptions.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/routers/validateScreenOptions'>;
}
declare module '@react-navigation/core/dist/StateUtils.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/StateUtils'>;
}
declare module '@react-navigation/core/dist/utils/docsUrl.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/utils/docsUrl'>;
}
declare module '@react-navigation/core/dist/utils/getActiveChildNavigationOptions.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/utils/getActiveChildNavigationOptions'>;
}
declare module '@react-navigation/core/dist/utils/getSceneIndicesForInterpolationInputRange.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/utils/getSceneIndicesForInterpolationInputRange'>;
}
declare module '@react-navigation/core/dist/utils/invariant.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/utils/invariant'>;
}
declare module '@react-navigation/core/dist/utils/withDefaultValue.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/utils/withDefaultValue'>;
}
declare module '@react-navigation/core/dist/views/NavigationConsumer.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/NavigationConsumer'>;
}
declare module '@react-navigation/core/dist/views/NavigationContext.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/NavigationContext'>;
}
declare module '@react-navigation/core/dist/views/NavigationEvents.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/NavigationEvents'>;
}
declare module '@react-navigation/core/dist/views/NavigationProvider.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/NavigationProvider'>;
}
declare module '@react-navigation/core/dist/views/SceneView.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/SceneView'>;
}
declare module '@react-navigation/core/dist/views/SwitchView/SwitchView.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/SwitchView/SwitchView'>;
}
declare module '@react-navigation/core/dist/views/withNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/withNavigation'>;
}
declare module '@react-navigation/core/dist/views/withNavigationFocus.js' {
  declare module.exports: $Exports<'@react-navigation/core/dist/views/withNavigationFocus'>;
}
declare module '@react-navigation/core/src/__tests__/getChildEventSubscriber-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/__tests__/getChildEventSubscriber-test'>;
}
declare module '@react-navigation/core/src/__tests__/getNavigation-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/__tests__/getNavigation-test'>;
}
declare module '@react-navigation/core/src/__tests__/NavigationActions-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/__tests__/NavigationActions-test'>;
}
declare module '@react-navigation/core/src/__tests__/NavigationStateUtils-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/__tests__/NavigationStateUtils-test'>;
}
declare module '@react-navigation/core/src/getChildEventSubscriber.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/getChildEventSubscriber'>;
}
declare module '@react-navigation/core/src/getChildNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/getChildNavigation'>;
}
declare module '@react-navigation/core/src/getChildrenNavigationCache.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/getChildrenNavigationCache'>;
}
declare module '@react-navigation/core/src/getNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/getNavigation'>;
}
declare module '@react-navigation/core/src/index.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/index'>;
}
declare module '@react-navigation/core/src/NavigationActions.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/NavigationActions'>;
}
declare module '@react-navigation/core/src/navigators/createNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/navigators/createNavigator'>;
}
declare module '@react-navigation/core/src/navigators/createSwitchNavigator.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/navigators/createSwitchNavigator'>;
}
declare module '@react-navigation/core/src/routers/__tests__/createConfigGetter-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/createConfigGetter-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/PathHandling-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/PathHandling-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/pathUtils-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/pathUtils-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/Routers-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/Routers-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/StackRouter-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/StackRouter-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/SwitchRouter-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/SwitchRouter-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/TabRouter-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/TabRouter-test'>;
}
declare module '@react-navigation/core/src/routers/__tests__/validateRouteConfigMap-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/__tests__/validateRouteConfigMap-test'>;
}
declare module '@react-navigation/core/src/routers/createConfigGetter.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/createConfigGetter'>;
}
declare module '@react-navigation/core/src/routers/getNavigationActionCreators.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/getNavigationActionCreators'>;
}
declare module '@react-navigation/core/src/routers/getScreenForRouteName.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/getScreenForRouteName'>;
}
declare module '@react-navigation/core/src/routers/pathUtils.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/pathUtils'>;
}
declare module '@react-navigation/core/src/routers/StackActions.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/StackActions'>;
}
declare module '@react-navigation/core/src/routers/StackRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/StackRouter'>;
}
declare module '@react-navigation/core/src/routers/SwitchRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/SwitchRouter'>;
}
declare module '@react-navigation/core/src/routers/TabRouter.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/TabRouter'>;
}
declare module '@react-navigation/core/src/routers/validateRouteConfigMap.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/validateRouteConfigMap'>;
}
declare module '@react-navigation/core/src/routers/validateScreenOptions.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/routers/validateScreenOptions'>;
}
declare module '@react-navigation/core/src/StateUtils.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/StateUtils'>;
}
declare module '@react-navigation/core/src/utils/docsUrl.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/utils/docsUrl'>;
}
declare module '@react-navigation/core/src/utils/getActiveChildNavigationOptions.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/utils/getActiveChildNavigationOptions'>;
}
declare module '@react-navigation/core/src/utils/getSceneIndicesForInterpolationInputRange.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/utils/getSceneIndicesForInterpolationInputRange'>;
}
declare module '@react-navigation/core/src/utils/invariant.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/utils/invariant'>;
}
declare module '@react-navigation/core/src/utils/withDefaultValue.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/utils/withDefaultValue'>;
}
declare module '@react-navigation/core/src/views/__tests__/NavigationEvents-test.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/__tests__/NavigationEvents-test'>;
}
declare module '@react-navigation/core/src/views/NavigationConsumer.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/NavigationConsumer'>;
}
declare module '@react-navigation/core/src/views/NavigationContext.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/NavigationContext'>;
}
declare module '@react-navigation/core/src/views/NavigationEvents.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/NavigationEvents'>;
}
declare module '@react-navigation/core/src/views/NavigationProvider.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/NavigationProvider'>;
}
declare module '@react-navigation/core/src/views/SceneView.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/SceneView'>;
}
declare module '@react-navigation/core/src/views/SwitchView/SwitchView.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/SwitchView/SwitchView'>;
}
declare module '@react-navigation/core/src/views/withNavigation.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/withNavigation'>;
}
declare module '@react-navigation/core/src/views/withNavigationFocus.js' {
  declare module.exports: $Exports<'@react-navigation/core/src/views/withNavigationFocus'>;
}
