// flow-typed signature: 6afd15d96d524b48dd70fa758373d370
// flow-typed version: <<STUB>>/@react-navigation/web_v^1.0.0-alpha.7/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-navigation/web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-navigation/web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-navigation/web/dist/createBrowserApp' {
  declare module.exports: any;
}

declare module '@react-navigation/web/dist/handleServerRequest' {
  declare module.exports: any;
}

declare module '@react-navigation/web/dist/index' {
  declare module.exports: any;
}

declare module '@react-navigation/web/dist/Link' {
  declare module.exports: any;
}

declare module '@react-navigation/web/src/__tests__/createBrowserApp-test' {
  declare module.exports: any;
}

declare module '@react-navigation/web/src/createBrowserApp' {
  declare module.exports: any;
}

declare module '@react-navigation/web/src/handleServerRequest' {
  declare module.exports: any;
}

declare module '@react-navigation/web/src/index' {
  declare module.exports: any;
}

declare module '@react-navigation/web/src/Link' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-navigation/web/dist/createBrowserApp.js' {
  declare module.exports: $Exports<'@react-navigation/web/dist/createBrowserApp'>;
}
declare module '@react-navigation/web/dist/handleServerRequest.js' {
  declare module.exports: $Exports<'@react-navigation/web/dist/handleServerRequest'>;
}
declare module '@react-navigation/web/dist/index.js' {
  declare module.exports: $Exports<'@react-navigation/web/dist/index'>;
}
declare module '@react-navigation/web/dist/Link.js' {
  declare module.exports: $Exports<'@react-navigation/web/dist/Link'>;
}
declare module '@react-navigation/web/src/__tests__/createBrowserApp-test.js' {
  declare module.exports: $Exports<'@react-navigation/web/src/__tests__/createBrowserApp-test'>;
}
declare module '@react-navigation/web/src/createBrowserApp.js' {
  declare module.exports: $Exports<'@react-navigation/web/src/createBrowserApp'>;
}
declare module '@react-navigation/web/src/handleServerRequest.js' {
  declare module.exports: $Exports<'@react-navigation/web/src/handleServerRequest'>;
}
declare module '@react-navigation/web/src/index.js' {
  declare module.exports: $Exports<'@react-navigation/web/src/index'>;
}
declare module '@react-navigation/web/src/Link.js' {
  declare module.exports: $Exports<'@react-navigation/web/src/Link'>;
}
