// flow-typed signature: 5f20dde9fb9724369df8ba064ae5f5be
// flow-typed version: <<STUB>>/libphonenumber-js/mobile_v1.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libphonenumber-js/mobile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libphonenumber-js/mobile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libphonenumber-js/mobile/index.commonjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libphonenumber-js/mobile/index.commonjs.js' {
  declare module.exports: $Exports<'libphonenumber-js/mobile/index.commonjs'>;
}
declare module 'libphonenumber-js/mobile/index' {
  declare module.exports: $Exports<'libphonenumber-js/mobile'>;
}
declare module 'libphonenumber-js/mobile/index.js' {
  declare module.exports: $Exports<'libphonenumber-js/mobile'>;
}
